In [1]:
import pandas as pd
import numpy as np

## Additional Data Merging

Adding additional data to the test/train set and creating larger groupings of age/income stats.

In [2]:
def update_tract(x):
    tract = str(x)
    if len(tract) < 11:
        tract = "0" + tract
    return tract

In [3]:
train = pd.read_csv("../data/broadband_training_bin_1.csv", converters={"tract_geoid" : lambda x: update_tract(x),
                                                                       'All_Providers' : lambda x: x.replace("{","").replace("}", "").split(", ")})
train.head()

,tract_geoid,All_Provider_Count,All_Providers,MaxAdDown,MaxAdUp,AllMaxAdDown,AllMaxAdUp,Wired_Provider_Count,Satellite_Provider_Count,Fixed_Wireless_Provider_Count,...,Secondary RUCA Code - 99.0,Secondary RUCA Code - 7.1,Secondary RUCA Code - 10.2,Secondary RUCA Code - 2.1,Secondary RUCA Code - 10.1,Secondary RUCA Code - 10.3,Secondary RUCA Code - 7.2,Secondary RUCA Code - 5.1,Secondary RUCA Code - 8.1,Secondary RUCA Code - 8.2
0,06099000201,11,"[56004, 56838, 54694, 54411, 67057, 59349, 555...",1000.0,1000.0,"{0.0, 0.768, 1.5, 3.0, 100.0, 5.0, 6.0, 2.0, 1...","{0.0, 0.512, 0.768, 3.0, 35.0, 5.0, 0.384, 7.0...",4.0,4,4.0,...,0,0,0,0,0,0,0,0,0,0
1,47125102002,7,"[56004, 54694, 67056, 59349, 55574, 55262, 58623]",1000.0,1000.0,"{0.0, 2.0, 100.0, 6.0, 1000.0, 75.0, 940.0, 12...","{0.0, 0.768, 0.512, 3.0, 35.0, 2.0, 5.0, 1.3, ...",3.0,4,0.0,...,0,0,0,0,0,0,0,0,0,0
2,22019001300,8,"[56004, 54694, 67056, 59349, 55262, 53788, 554...",1000.0,1000.0,"{0.0, 1.5, 2.0, 3.0, 5.0, 6.0, 9.0, 10.0, 12.0...","{0.0, 0.512, 2.0, 3.0, 0.384, 0.128, 0.768, 0....",3.0,4,2.0,...,0,0,0,0,0,0,0,0,0,0
3,18083955400,11,"[53888, 59424, 56004, 54694, 67053, 59534, 646...",1000.0,1000.0,"{0.0, 1.5, 2.0, 35.0, 3.0, 6.0, 1000.0, 10.0, ...","{0.0, 0.512, 2.0, 3.0, 0.384, 0.128, 0.768, 0....",5.0,4,3.0,...,0,0,0,0,0,0,0,0,0,0
4,39085206600,7,"[56004, 54694, 54895, 67059, 59349, 55262, 58623]",1000.0,1000.0,"{0.0, 2.0, 3.0, 35.0, 100.0, 6.0, 1000.0, 75.0...","{0.0, 0.384, 0.512, 35.0, 3.0, 0.768, 2.0, 5.0...",3.0,4,0.0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
test = pd.read_csv("../data/broadband_test_bin_1.csv", converters={"tract_geoid" : lambda x: update_tract(x),
                                                                  'All_Providers' : lambda x: x.replace("{","").replace("}", "").split(", ")})
test.head()

,tract_geoid,All_Provider_Count,All_Providers,MaxAdDown,MaxAdUp,AllMaxAdDown,AllMaxAdUp,Wired_Provider_Count,Satellite_Provider_Count,Fixed_Wireless_Provider_Count,...,Secondary RUCA Code - 99.0,Secondary RUCA Code - 7.1,Secondary RUCA Code - 10.2,Secondary RUCA Code - 2.1,Secondary RUCA Code - 10.1,Secondary RUCA Code - 10.3,Secondary RUCA Code - 7.2,Secondary RUCA Code - 5.1,Secondary RUCA Code - 8.1,Secondary RUCA Code - 8.2
0,26099245300,12,"[56004, 54694, 58025, 67054, 55027, 54836, 593...",1000.0,1000.0,"{0.0, 2.0, 3.0, 100.0, 5.0, 6.0, 1000.0, 75.0,...","{0.0, 0.512, 0.384, 3.0, 35.0, 0.768, 2.0, 0.6...",7.0,4,1.0,...,0,0,0,0,0,0,0,0,0,0
1,46005956900,12,"[56004, 58876, 54694, 57231, 54263, 56435, 579...",1000.0,250.0,"{0.0, 2.0, 35.0, 3.0, 6.0, 40.0, 1000.0, 10.0,...","{0.0, 1.0, 2.0, 3.0, 0.5, 0.64, 6.0, 1.5, 8.0,...",5.0,4,3.0,...,0,0,0,0,0,0,0,0,0,0
2,04019004312,12,"[56004, 57317, 58876, 54694, 58888, 57292, 598...",1000.0,940.0,"{0.0, 1.5, 2.0, 3.0, 5.0, 6.0, 7.0, 10.0, 12.0...","{0.0, 0.896, 2.0, 3.0, 35.0, 5.0, 0.5, 7.0, 1....",4.0,4,4.0,...,0,0,0,0,0,0,0,0,0,0
3,09001257200,13,"[54788, 56004, 54076, 56006, 54694, 56300, 548...",500.0,115.0,"{0.0, 2.0, 35.0, 100.0, 6.0, 70.0, 200.0, 300....","{0.0, 1.0, 1.3, 35.0, 3.0, 5.0, 7.0, 115.0}",9.0,4,0.0,...,0,0,0,0,0,0,0,0,0,0
4,12001002102,6,"[56004, 54469, 54694, 67056, 59349, 55262]",100.0,100.0,"{0.768, 1.5, 0.0, 3.0, 100.0, 2.0, 6.0, 10.0, ...","{0.76, 1.0, 0.512, 3.0, 100.0, 0.384, 0.128, 0...",2.0,4,1.0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
train.shape

(56671, 166)

In [6]:
test.shape

(14168, 166)

In [7]:
ddi = pd.read_excel("../data/DDI_export_2019 - Copy.xlsx", sheet_name="US Tracts", converters= {"FIPS" : lambda x: str(x)})
ddi.head()

          FIPS  FIPS_Cnty Cnty_Name  St_Name         SE       INFA        DDI
0  01001020100       1001   Autauga  Alabama  21.268235  23.662166  21.185940
1  01001020200       1001   Autauga  Alabama  21.447970  28.664205  23.592654
2  01001020300       1001   Autauga  Alabama  28.874159  18.860859  23.346014
3  01001020400       1001   Autauga  Alabama  20.653305  15.321800  16.991838
4  01001020500       1001   Autauga  Alabama  17.752016  11.633832  13.626196

In [8]:
## Step 1: Merge DDI Data

new_train = train.merge(ddi[["FIPS", "SE", "INFA", "DDI"]], how="left", left_on="tract_geoid", right_on = "FIPS")
new_train.head()

,tract_geoid,All_Provider_Count,All_Providers,MaxAdDown,MaxAdUp,AllMaxAdDown,AllMaxAdUp,Wired_Provider_Count,Satellite_Provider_Count,Fixed_Wireless_Provider_Count,...,Secondary RUCA Code - 10.1,Secondary RUCA Code - 10.3,Secondary RUCA Code - 7.2,Secondary RUCA Code - 5.1,Secondary RUCA Code - 8.1,Secondary RUCA Code - 8.2,FIPS,SE,INFA,DDI
0,06099000201,11,"[56004, 56838, 54694, 54411, 67057, 59349, 555...",1000.0,1000.0,"{0.0, 0.768, 1.5, 3.0, 100.0, 5.0, 6.0, 2.0, 1...","{0.0, 0.512, 0.768, 3.0, 35.0, 5.0, 0.384, 7.0...",4.0,4,4.0,...,0,0,0,0,0,0,06099000201,14.764045,17.092088,14.422542
1,47125102002,7,"[56004, 54694, 67056, 59349, 55574, 55262, 58623]",1000.0,1000.0,"{0.0, 2.0, 100.0, 6.0, 1000.0, 75.0, 940.0, 12...","{0.0, 0.768, 0.512, 3.0, 35.0, 2.0, 5.0, 1.3, ...",3.0,4,0.0,...,0,0,0,0,0,0,47125102002,13.347344,10.511057,10.577836
2,22019001300,8,"[56004, 54694, 67056, 59349, 55262, 53788, 554...",1000.0,1000.0,"{0.0, 1.5, 2.0, 3.0, 5.0, 6.0, 9.0, 10.0, 12.0...","{0.0, 0.512, 2.0, 3.0, 0.384, 0.128, 0.768, 0....",3.0,4,2.0,...,0,0,0,0,0,0,22019001300,19.226805,13.412742,15.292926
3,18083955400,11,"[53888, 59424, 56004, 54694, 67053, 59534, 646...",1000.0,1000.0,"{0.0, 1.5, 2.0, 35.0, 3.0, 6.0, 1000.0, 10.0, ...","{0.0, 0.512, 2.0, 3.0, 0.384, 0.128, 0.768, 0....",5.0,4,3.0,...,0,0,0,0,0,0,18083955400,30.122784,22.652613,25.809677
4,39085206600,7,"[56004, 54694, 54895, 67059, 59349, 55262, 58623]",1000.0,1000.0,"{0.0, 2.0, 3.0, 35.0, 100.0, 6.0, 1000.0, 75.0...","{0.0, 0.384, 0.512, 35.0, 3.0, 0.768, 2.0, 5.0...",3.0,4,0.0,...,0,0,0,0,0,0,39085206600,20.651248,20.069225,19.176828

In [9]:
new_train.isnull().sum()

tract_geoid                  0
All_Provider_Count           0
All_Providers                0
MaxAdDown                    0
MaxAdUp                      0
                            ..
Secondary RUCA Code - 8.2    0
FIPS                         1
SE                           1
INFA                         1
DDI                          1
Length: 170, dtype: int64

In [10]:
## Now one row is missing. let's drop it

new_train[new_train.FIPS.isna()][["tract_geoid", "total_population"]]

       tract_geoid  total_population
15151  04007001300            1142.0

In [11]:
new_train = new_train[~new_train.FIPS.isna()]

In [12]:
new_test = test.merge(ddi[["FIPS", "SE", "INFA", "DDI"]], how="left", left_on="tract_geoid", right_on = "FIPS")
new_test.head()

,tract_geoid,All_Provider_Count,All_Providers,MaxAdDown,MaxAdUp,AllMaxAdDown,AllMaxAdUp,Wired_Provider_Count,Satellite_Provider_Count,Fixed_Wireless_Provider_Count,...,Secondary RUCA Code - 10.1,Secondary RUCA Code - 10.3,Secondary RUCA Code - 7.2,Secondary RUCA Code - 5.1,Secondary RUCA Code - 8.1,Secondary RUCA Code - 8.2,FIPS,SE,INFA,DDI
0,26099245300,12,"[56004, 54694, 58025, 67054, 55027, 54836, 593...",1000.0,1000.0,"{0.0, 2.0, 3.0, 100.0, 5.0, 6.0, 1000.0, 75.0,...","{0.0, 0.512, 0.384, 3.0, 35.0, 0.768, 2.0, 0.6...",7.0,4,1.0,...,0,0,0,0,0,0,26099245300,23.422555,19.034599,20.293031
1,46005956900,12,"[56004, 58876, 54694, 57231, 54263, 56435, 579...",1000.0,250.0,"{0.0, 2.0, 35.0, 3.0, 6.0, 40.0, 1000.0, 10.0,...","{0.0, 1.0, 2.0, 3.0, 0.5, 0.64, 6.0, 1.5, 8.0,...",5.0,4,3.0,...,0,0,0,0,0,0,46005956900,19.116258,24.626401,20.393245
2,04019004312,12,"[56004, 57317, 58876, 54694, 58888, 57292, 598...",1000.0,940.0,"{0.0, 1.5, 2.0, 3.0, 5.0, 6.0, 7.0, 10.0, 12.0...","{0.0, 0.896, 2.0, 3.0, 35.0, 5.0, 0.5, 7.0, 1....",4.0,4,4.0,...,0,0,0,0,0,0,04019004312,24.630586,17.341022,20.207390
3,09001257200,13,"[54788, 56004, 54076, 56006, 54694, 56300, 548...",500.0,115.0,"{0.0, 2.0, 35.0, 100.0, 6.0, 70.0, 200.0, 300....","{0.0, 1.0, 1.3, 35.0, 3.0, 5.0, 7.0, 115.0}",9.0,4,0.0,...,0,0,0,0,0,0,09001257200,20.180257,20.674751,19.184995
4,12001002102,6,"[56004, 54469, 54694, 67056, 59349, 55262]",100.0,100.0,"{0.768, 1.5, 0.0, 3.0, 100.0, 2.0, 6.0, 10.0, ...","{0.76, 1.0, 0.512, 3.0, 100.0, 0.384, 0.128, 0...",2.0,4,1.0,...,0,0,0,0,0,0,12001002102,26.264277,39.560742,31.378358

In [13]:
new_test.isnull().sum()

tract_geoid                  0
All_Provider_Count           0
All_Providers                0
MaxAdDown                    0
MaxAdUp                      0
                            ..
Secondary RUCA Code - 8.2    0
FIPS                         0
SE                           0
INFA                         0
DDI                          0
Length: 170, dtype: int64

In [14]:
## Step 2: Make bigger buckets of income and age
pd.set_option('display.max_rows', None)
new_train.columns.to_list()

['tract_geoid',
 'All_Provider_Count',
 'All_Providers',
 'MaxAdDown',
 'MaxAdUp',
 'AllMaxAdDown',
 'AllMaxAdUp',
 'Wired_Provider_Count',
 'Satellite_Provider_Count',
 'Fixed_Wireless_Provider_Count',
 'All_Provider_Count_25',
 'All_Provider_Count_100',
 'Fixed_Wireless_Provider_Count_25',
 'Wired_Provider_Count_25',
 'Satellite_Provider_Count_25',
 'Fixed_Wireless_Provider_Count_100',
 'Wired_Provider_Count_100',
 'Satellite_Provider_Count_100',
 'NAME',
 'median_age_overall',
 'median_age_male',
 'median_age_female',
 'state',
 'county',
 'tract',
 'employment_rate',
 'median_income',
 'total_households',
 'ave_household_size',
 'ave_family_size',
 'pct_health_ins_children',
 'pct_health_ins_19_64',
 'pct_health_ins_65+',
 'total_population',
 'median_house_value',
 'pct_white',
 'pct_hisp_latino',
 'pct_black',
 'pct_native',
 'pct_asian',
 'pct_hi_pi',
 'pct_other_race',
 'pct_two+_race',
 'pct_rent_burdened',
 'poverty_rate',
 'pct_pop_bachelors+',
 'pct_pop_hs+',
 'pct_internet',
 'pct_internet_dial_up',
 'pct_internet_broadband_any_type',
 'pct_internet_cellular',
 'pct_only_cellular',
 'pct_internet_broadband_fiber',
 'pct_internet_broadband_satellite',
 'pct_internet_only_satellite',
 'pct_internet_other',
 'pct_internet_no_subscrp',
 'pct_internet_none',
 'pct_computer',
 'pct_computer_with_dialup',
 'pct_computer_with_broadband',
 'pct_computer_no_internet',
 'pct_no_computer',
 'ALAND',
 'AWATER',
 'ALAND_SQMI',
 'AWATER_SQMI',
 'population_density',
 'pct_pop_ged',
 'pct_pop_some_college',
 'pct_pop_associates',
 'pct_pop_ssi_households',
 'pct_pop_lt_10k',
 'pct_pop_10k_thru_15k',
 'pct_pop_15k_thru_20k',
 'pct_pop_20k_thru_25k',
 'pct_pop_25k_thru_30k',
 'pct_pop_30k_thru_35k',
 'pct_pop_35k_thru_40k',
 'pct_pop_40k_thru_45k',
 'pct_pop_45k_thru_50k',
 'pct_pop_50k_thru_60k',
 'pct_pop_60k_thru_75k',
 'pct_pop_75k_thru_100k',
 'pct_pop_100k_thru_125k',
 'pct_pop_125k_thru_150k',
 'pct_pop_150k_thru_200k',
 'pct_pop_gt_200k',
 'pct_pop_lt_5',
 'pct_pop_5_to_9',
 'pct_pop_10_to_14',
 'pct_pop_15_to_19',
 'pct_pop_20_to_24',
 'pct_pop_25_to_29',
 'pct_pop_30_to_34',
 'pct_pop_35_to_39',
 'pct_pop_40_to_44',
 'pct_pop_45_to_49',
 'pct_pop_50_to_54',
 'pct_pop_55_to_59',
 'pct_pop_60_to_64',
 'pct_pop_65_to_69',
 'pct_pop_70_to_74',
 'pct_pop_75_to_79',
 'pct_pop_80_to_84',
 'pct_pop_gt_85',
 'pct_pop_disability',
 'pct_pop_households_with_kids',
 'pct_pop_foreign_born',
 'Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 'Form 477 All Terrestrial Broadband: Max Advertised Consumer Upload Speed (Mbps)',
 'Ookla Median Download Speed (Mbps)',
 'Ookla Median Upload Speed (Mbps)',
 'Primary RUCA Code 2010',
 'Secondary RUCA Code, 2010 (see errata)',
 '0_5_providers',
 '6_10_providers',
 '11_15_providers',
 '16_20_providers',
 '20+_providers',
 '0_25_MaxAdDown',
 '25_99_MaxAdDown',
 '99_499_MaxAdDown',
 '499_inf_MaxAdDown',
 '0_25_Ookla Median Download Speed (Mbps)',
 '25_99_Ookla Median Download Speed (Mbps)',
 '99_499_Ookla Median Download Speed (Mbps)',
 '499_inf_Ookla Median Download Speed (Mbps)',
 '0_25_Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 '25_99_Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 '99_499_Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 '499_inf_Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 'single_provider',
 'Primary RUCA Code - 1.0',
 'Primary RUCA Code - 2.0',
 'Primary RUCA Code - 4.0',
 'Primary RUCA Code - 10.0',
 'Primary RUCA Code - 7.0',
 'Primary RUCA Code - 5.0',
 'Primary RUCA Code - 8.0',
 'Primary RUCA Code - 3.0',
 'Primary RUCA Code - 6.0',
 'Primary RUCA Code - 9.0',
 'Primary RUCA Code - 99.0',
 'Secondary RUCA Code - 1.0',
 'Secondary RUCA Code - 2.0',
 'Secondary RUCA Code - 4.0',
 'Secondary RUCA Code - 10.0',
 'Secondary RUCA Code - 7.0',
 'Secondary RUCA Code - 5.0',
 'Secondary RUCA Code - 1.1',
 'Secondary RUCA Code - 8.0',
 'Secondary RUCA Code - 3.0',
 'Secondary RUCA Code - 6.0',
 'Secondary RUCA Code - 9.0',
 'Secondary RUCA Code - 4.1',
 'Secondary RUCA Code - 99.0',
 'Secondary RUCA Code - 7.1',
 'Secondary RUCA Code - 10.2',
 'Secondary RUCA Code - 2.1',
 'Secondary RUCA Code - 10.1',
 'Secondary RUCA Code - 10.3',
 'Secondary RUCA Code - 7.2',
 'Secondary RUCA Code - 5.1',
 'Secondary RUCA Code - 8.1',
 'Secondary RUCA Code - 8.2',
 'FIPS',
 'SE',
 'INFA',
 'DDI']

In [15]:
## Add additional columns for incomes

new_train['pct_pop_income_lt_50k'] = (new_train['pct_pop_lt_10k'] + new_train['pct_pop_10k_thru_15k'] +
                                  new_train['pct_pop_15k_thru_20k'] + new_train['pct_pop_20k_thru_25k'] + 
                                  new_train['pct_pop_25k_thru_30k'] + new_train['pct_pop_30k_thru_35k'] +
                                  new_train['pct_pop_35k_thru_40k'] + new_train['pct_pop_40k_thru_45k'] +
                                  new_train['pct_pop_45k_thru_50k']
                                 )

new_train['pct_pop_income_lt_30k'] = (new_train['pct_pop_lt_10k'] + new_train['pct_pop_10k_thru_15k'] +
                                  new_train['pct_pop_15k_thru_20k'] + new_train['pct_pop_20k_thru_25k'] + 
                                  new_train['pct_pop_25k_thru_30k']
                                 )

new_train['pct_pop_income_gt_100k'] = (new_train['pct_pop_100k_thru_125k'] + new_train['pct_pop_125k_thru_150k'] +
                                   new_train['pct_pop_150k_thru_200k'] + new_train['pct_pop_gt_200k']
                                 )

new_test['pct_pop_income_lt_50k'] = (new_test['pct_pop_lt_10k'] + new_test['pct_pop_10k_thru_15k'] +
                                  new_test['pct_pop_15k_thru_20k'] + new_test['pct_pop_20k_thru_25k'] + 
                                  new_test['pct_pop_25k_thru_30k'] + new_test['pct_pop_30k_thru_35k'] +
                                  new_test['pct_pop_35k_thru_40k'] + new_test['pct_pop_40k_thru_45k'] +
                                  new_test['pct_pop_45k_thru_50k']
                                 )

new_test['pct_pop_income_lt_30k'] = (new_test['pct_pop_lt_10k'] + new_test['pct_pop_10k_thru_15k'] +
                                  new_test['pct_pop_15k_thru_20k'] + new_test['pct_pop_20k_thru_25k'] + 
                                  new_test['pct_pop_25k_thru_30k']
                                 )

new_test['pct_pop_income_gt_100k'] = (new_test['pct_pop_100k_thru_125k'] + new_test['pct_pop_125k_thru_150k'] +
                                   new_test['pct_pop_150k_thru_200k'] + new_test['pct_pop_gt_200k'])

In [16]:
## Add additional columns for ages

new_train["pct_ages_gt_50"] = (new_train['pct_pop_50_to_54'] + new_train['pct_pop_55_to_59'] + new_train['pct_pop_60_to_64'] +
                           new_train['pct_pop_65_to_69'] + new_train['pct_pop_70_to_74'] + new_train['pct_pop_75_to_79'] + 
                           new_train['pct_pop_80_to_84'] + new_train['pct_pop_gt_85']
                                     )

new_train["pct_ages_lt_19"] = (new_train['pct_pop_lt_5'] + new_train['pct_pop_5_to_9']+ new_train['pct_pop_10_to_14']+
                               new_train['pct_pop_15_to_19'] )


new_test["pct_ages_gt_50"] = (new_test['pct_pop_50_to_54'] + new_test['pct_pop_55_to_59'] + new_test['pct_pop_60_to_64'] +
                           new_test['pct_pop_65_to_69'] + new_test['pct_pop_70_to_74'] + new_test['pct_pop_75_to_79'] + 
                           new_test['pct_pop_80_to_84'] + new_test['pct_pop_gt_85']
                                     )

new_test["pct_ages_lt_19"] = (new_test['pct_pop_lt_5'] + new_test['pct_pop_5_to_9']+ new_test['pct_pop_10_to_14']+ 
                              new_test['pct_pop_15_to_19'])

In [17]:
## Step 3: RUCA aggregation

new_train["ruca_metro"] = new_train["Primary RUCA Code 2010"].apply(lambda x: x<=3)
new_train["ruca_micro"] = new_train["Primary RUCA Code 2010"].apply(lambda x: x>=4 and x<=6)
new_train["ruca_small_town"] = new_train["Primary RUCA Code 2010"].apply(lambda x: x>=7 and x<=9)
new_train["ruca_rural"] = new_train["Primary RUCA Code 2010"].apply(lambda x: x==10)


new_test["ruca_metro"] = new_test["Primary RUCA Code 2010"].apply(lambda x: x<=3)
new_test["ruca_micro"] = new_test["Primary RUCA Code 2010"].apply(lambda x: x>=4 and x<=6)
new_test["ruca_small_town"] = new_test["Primary RUCA Code 2010"].apply(lambda x: x>=7 and x<=9)
new_test["ruca_rural"] = new_test["Primary RUCA Code 2010"].apply(lambda x: x==10)

In [18]:
## Step 4: Add booleans for big providers

def check_for_att(row):
    if len(row) > 0:
        for i in row:
            #print(i)
            if int(i) > 67052:
                return True
    return False

In [19]:

new_train["Comcast_present"] = new_train["All_Providers"].apply(lambda row: '55574' in row)

new_test["Comcast_present"] = new_test["All_Providers"].apply(lambda row: '55574' in row)

new_train["ATT_present"] = new_train["All_Providers"].apply(check_for_att)

new_test["ATT_present"] = new_test["All_Providers"].apply(check_for_att)

new_train["HughesNet_present"] = new_train["All_Providers"].apply(lambda row: '54694' in row)

new_test["HughesNet_present"] = new_test["All_Providers"].apply(lambda row: '54694' in row)

new_train["GCI_Comm_Corp_present"] = new_train["All_Providers"].apply(lambda row: '59349' in row)

new_test["GCI_Comm_Corp_present"] = new_test["All_Providers"].apply(lambda row: '59349' in row)

new_train["ViaSat_present"] = new_train["All_Providers"].apply(lambda row: '56004' in row)

new_test["ViaSat_present"] = new_test["All_Providers"].apply(lambda row: '56004' in row)

new_train["VSAT_present"] = new_train["All_Providers"].apply(lambda row: '55262' in row)

new_test["VSAT_present"] = new_test["All_Providers"].apply(lambda row: '55262' in row)

new_train["Century_Link_present"] = new_train["All_Providers"].apply(lambda row: '53788' in row)

new_test["Century_Link_present"] = new_test["All_Providers"].apply(lambda row: '53788' in row)

new_train["Spectrum_present"] = new_train["All_Providers"].apply(lambda row: '58623' in row)

new_test["Spectrum_present"] = new_test["All_Providers"].apply(lambda row: '58623' in row)

new_train["Crown_Castle_present"] = new_train["All_Providers"].apply(lambda row: '55027' in row)

new_test["Crown_Castle_present"] = new_test["All_Providers"].apply(lambda row: '55027' in row)

new_train["Etheric_present"] = new_train["All_Providers"].apply(lambda row: '57777' in row)

new_test["Etheric_present"] = new_test["All_Providers"].apply(lambda row: '57777' in row)

new_train["Frontier_Communications_present"] = new_train["All_Providers"].apply(lambda row: ('59351' in row) or 
                                                                               ('59347' in row))

new_test["Frontier_Communications_present"] = new_test["All_Providers"].apply(lambda row: ('59351' in row) or 
                                                                               ('59347' in row))

In [20]:
new_train.columns.to_list()

['tract_geoid',
 'All_Provider_Count',
 'All_Providers',
 'MaxAdDown',
 'MaxAdUp',
 'AllMaxAdDown',
 'AllMaxAdUp',
 'Wired_Provider_Count',
 'Satellite_Provider_Count',
 'Fixed_Wireless_Provider_Count',
 'All_Provider_Count_25',
 'All_Provider_Count_100',
 'Fixed_Wireless_Provider_Count_25',
 'Wired_Provider_Count_25',
 'Satellite_Provider_Count_25',
 'Fixed_Wireless_Provider_Count_100',
 'Wired_Provider_Count_100',
 'Satellite_Provider_Count_100',
 'NAME',
 'median_age_overall',
 'median_age_male',
 'median_age_female',
 'state',
 'county',
 'tract',
 'employment_rate',
 'median_income',
 'total_households',
 'ave_household_size',
 'ave_family_size',
 'pct_health_ins_children',
 'pct_health_ins_19_64',
 'pct_health_ins_65+',
 'total_population',
 'median_house_value',
 'pct_white',
 'pct_hisp_latino',
 'pct_black',
 'pct_native',
 'pct_asian',
 'pct_hi_pi',
 'pct_other_race',
 'pct_two+_race',
 'pct_rent_burdened',
 'poverty_rate',
 'pct_pop_bachelors+',
 'pct_pop_hs+',
 'pct_internet',
 'pct_internet_dial_up',
 'pct_internet_broadband_any_type',
 'pct_internet_cellular',
 'pct_only_cellular',
 'pct_internet_broadband_fiber',
 'pct_internet_broadband_satellite',
 'pct_internet_only_satellite',
 'pct_internet_other',
 'pct_internet_no_subscrp',
 'pct_internet_none',
 'pct_computer',
 'pct_computer_with_dialup',
 'pct_computer_with_broadband',
 'pct_computer_no_internet',
 'pct_no_computer',
 'ALAND',
 'AWATER',
 'ALAND_SQMI',
 'AWATER_SQMI',
 'population_density',
 'pct_pop_ged',
 'pct_pop_some_college',
 'pct_pop_associates',
 'pct_pop_ssi_households',
 'pct_pop_lt_10k',
 'pct_pop_10k_thru_15k',
 'pct_pop_15k_thru_20k',
 'pct_pop_20k_thru_25k',
 'pct_pop_25k_thru_30k',
 'pct_pop_30k_thru_35k',
 'pct_pop_35k_thru_40k',
 'pct_pop_40k_thru_45k',
 'pct_pop_45k_thru_50k',
 'pct_pop_50k_thru_60k',
 'pct_pop_60k_thru_75k',
 'pct_pop_75k_thru_100k',
 'pct_pop_100k_thru_125k',
 'pct_pop_125k_thru_150k',
 'pct_pop_150k_thru_200k',
 'pct_pop_gt_200k',
 'pct_pop_lt_5',
 'pct_pop_5_to_9',
 'pct_pop_10_to_14',
 'pct_pop_15_to_19',
 'pct_pop_20_to_24',
 'pct_pop_25_to_29',
 'pct_pop_30_to_34',
 'pct_pop_35_to_39',
 'pct_pop_40_to_44',
 'pct_pop_45_to_49',
 'pct_pop_50_to_54',
 'pct_pop_55_to_59',
 'pct_pop_60_to_64',
 'pct_pop_65_to_69',
 'pct_pop_70_to_74',
 'pct_pop_75_to_79',
 'pct_pop_80_to_84',
 'pct_pop_gt_85',
 'pct_pop_disability',
 'pct_pop_households_with_kids',
 'pct_pop_foreign_born',
 'Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 'Form 477 All Terrestrial Broadband: Max Advertised Consumer Upload Speed (Mbps)',
 'Ookla Median Download Speed (Mbps)',
 'Ookla Median Upload Speed (Mbps)',
 'Primary RUCA Code 2010',
 'Secondary RUCA Code, 2010 (see errata)',
 '0_5_providers',
 '6_10_providers',
 '11_15_providers',
 '16_20_providers',
 '20+_providers',
 '0_25_MaxAdDown',
 '25_99_MaxAdDown',
 '99_499_MaxAdDown',
 '499_inf_MaxAdDown',
 '0_25_Ookla Median Download Speed (Mbps)',
 '25_99_Ookla Median Download Speed (Mbps)',
 '99_499_Ookla Median Download Speed (Mbps)',
 '499_inf_Ookla Median Download Speed (Mbps)',
 '0_25_Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 '25_99_Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 '99_499_Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 '499_inf_Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
 'single_provider',
 'Primary RUCA Code - 1.0',
 'Primary RUCA Code - 2.0',
 'Primary RUCA Code - 4.0',
 'Primary RUCA Code - 10.0',
 'Primary RUCA Code - 7.0',
 'Primary RUCA Code - 5.0',
 'Primary RUCA Code - 8.0',
 'Primary RUCA Code - 3.0',
 'Primary RUCA Code - 6.0',
 'Primary RUCA Code - 9.0',
 'Primary RUCA Code - 99.0',
 'Secondary RUCA Code - 1.0',
 'Secondary RUCA Code - 2.0',
 'Secondary RUCA Code - 4.0',
 'Secondary RUCA Code - 10.0',
 'Secondary RUCA Code - 7.0',
 'Secondary RUCA Code - 5.0',
 'Secondary RUCA Code - 1.1',
 'Secondary RUCA Code - 8.0',
 'Secondary RUCA Code - 3.0',
 'Secondary RUCA Code - 6.0',
 'Secondary RUCA Code - 9.0',
 'Secondary RUCA Code - 4.1',
 'Secondary RUCA Code - 99.0',
 'Secondary RUCA Code - 7.1',
 'Secondary RUCA Code - 10.2',
 'Secondary RUCA Code - 2.1',
 'Secondary RUCA Code - 10.1',
 'Secondary RUCA Code - 10.3',
 'Secondary RUCA Code - 7.2',
 'Secondary RUCA Code - 5.1',
 'Secondary RUCA Code - 8.1',
 'Secondary RUCA Code - 8.2',
 'FIPS',
 'SE',
 'INFA',
 'DDI',
 'pct_pop_income_lt_50k',
 'pct_pop_income_lt_30k',
 'pct_pop_income_gt_100k',
 'pct_ages_gt_50',
 'pct_ages_lt_19',
 'ruca_metro',
 'ruca_micro',
 'ruca_small_town',
 'ruca_rural',
 'Comcast_present',
 'ATT_present',
 'HughesNet_present',
 'GCI_Comm_Corp_present',
 'ViaSat_present',
 'VSAT_present',
 'Century_Link_present',
 'Spectrum_present',
 'Crown_Castle_present',
 'Etheric_present',
 'Frontier_Communications_present']

In [21]:
## Remove some columns

new_train = new_train.drop(columns=["FIPS", "All_Providers", "AllMaxAdDown", "AllMaxAdUp"])
new_test = new_test.drop(columns=["FIPS", "All_Providers", "AllMaxAdDown", "AllMaxAdUp"])

In [22]:
new_train.shape

(56670, 186)

In [23]:
new_test.shape

(14168, 186)

In [24]:
new_train.head()

,tract_geoid,All_Provider_Count,MaxAdDown,MaxAdUp,Wired_Provider_Count,Satellite_Provider_Count,Fixed_Wireless_Provider_Count,All_Provider_Count_25,All_Provider_Count_100,Fixed_Wireless_Provider_Count_25,...,ATT_present,HughesNet_present,GCI_Comm_Corp_present,ViaSat_present,VSAT_present,Century_Link_present,Spectrum_present,Crown_Castle_present,Etheric_present,Frontier_Communications_present
0,06099000201,11,1000.0,1000.0,4.0,4,4.0,7.0,3.0,3.0,...,True,True,True,True,True,False,False,False,False,False
1,47125102002,7,1000.0,1000.0,3.0,4,0.0,5.0,4.0,0.0,...,True,True,True,True,True,False,True,False,False,False
2,22019001300,8,1000.0,1000.0,3.0,4,2.0,4.0,2.0,0.0,...,True,True,True,True,True,True,False,False,False,False
3,18083955400,11,1000.0,1000.0,5.0,4,3.0,6.0,3.0,1.0,...,True,True,True,True,True,False,False,False,False,False
4,39085206600,7,1000.0,1000.0,3.0,4,0.0,4.0,2.0,0.0,...,True,True,True,True,True,False,True,False,False,False

In [25]:
new_test.head()

,tract_geoid,All_Provider_Count,MaxAdDown,MaxAdUp,Wired_Provider_Count,Satellite_Provider_Count,Fixed_Wireless_Provider_Count,All_Provider_Count_25,All_Provider_Count_100,Fixed_Wireless_Provider_Count_25,...,ATT_present,HughesNet_present,GCI_Comm_Corp_present,ViaSat_present,VSAT_present,Century_Link_present,Spectrum_present,Crown_Castle_present,Etheric_present,Frontier_Communications_present
0,26099245300,12,1000.0,1000.0,7.0,4,1.0,5.0,4.0,0.0,...,True,True,True,True,True,False,False,True,False,False
1,46005956900,12,1000.0,250.0,5.0,4,3.0,7.0,2.0,3.0,...,False,True,True,True,True,True,False,False,False,False
2,04019004312,12,1000.0,940.0,4.0,4,4.0,8.0,5.0,3.0,...,False,True,True,True,True,True,False,False,False,False
3,09001257200,13,500.0,115.0,9.0,4,0.0,4.0,2.0,0.0,...,False,True,True,True,True,True,False,True,False,True
4,12001002102,6,100.0,100.0,2.0,4,1.0,3.0,2.0,0.0,...,True,True,True,True,True,False,False,False,False,False

In [29]:
new_train.to_csv("../data/broadband_training_bin_2.csv", index=False)
new_test.to_csv("../data/broadband_test_bin_2.csv.csv", index=False)

In [28]:
all_data = pd.concat([new_train, new_test])
all_data.shape

(70838, 186)

In [ ]:
all_data.to_csv("../d")