In [1]:
import pandas as pd
import numpy as np

# Overview of this Notebook

This notebook is meant to be run on the data output of running the Data Gathering notebook in the census scripts folder which produced a csv file of census variable columns (such as B01002_001E, B01002_002E, etc...) for each census tract in the US. 

The list of variables we pulled is here: https://docs.google.com/document/d/1eslJJ1DKmmNkJAtZbOdxHAbHCZ34L6cb2tkgMoExPwc/edit?usp=sharing

In [4]:
data = pd.read_csv("../data/census_data_old.csv")
data

,NAME,B01003_001E,B01002_001E,B01002_002E,B01002_003E,B15003_001E,B15003_017E,B15003_018E,B15003_019E,B15003_020E,...,DP05_0001E,DP04_0089E,DP05_0077PE,DP05_0071PE,DP05_0078PE,DP05_0079PE,DP05_0080PE,DP05_0081PE,DP05_0082PE,DP05_0083PE
0,"Census Tract 11, Jefferson County, Alabama",4781,39.0,42.5,38.1,3285,552,201,269,534,...,4781,85500,1.6,0.4,96.8,1.2,0.0,0.0,0.0,0.0
1,"Census Tract 14, Jefferson County, Alabama",1946,44.3,40.5,49.1,1274,300,15,57,399,...,1946,67800,0.0,6.8,91.7,0.0,0.0,0.0,1.1,0.4
2,"Census Tract 20, Jefferson County, Alabama",4080,34.0,31.0,36.4,2802,720,134,267,571,...,4080,68400,27.7,7.5,63.8,0.0,0.0,0.0,0.0,0.9
3,"Census Tract 38.02, Jefferson County, Alabama",5291,35.8,31.7,37.3,3464,1294,32,221,551,...,5291,64100,1.6,0.0,97.5,0.0,0.0,0.0,0.0,0.9
4,"Census Tract 40, Jefferson County, Alabama",2533,52.1,51.6,53.8,1971,540,144,130,509,...,2533,67300,6.6,6.8,85.7,0.9,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73051,"Census Tract 19.02, Laramie County, Wyoming",4187,47.1,46.6,47.9,3075,506,181,275,539,...,4187,345200,93.3,4.3,0.0,0.0,0.0,0.0,0.0,2.5
73052,"Census Tract 9808.01, Laramie County, Wyoming",0,-666666666.0,-666666666.0,-666666666.0,0,0,0,0,0,...,0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0
73053,"Census Tract 16.02, Natrona County, Wyoming",7513,37.6,39.2,36.1,4786,1007,170,460,714,...,7513,321700,85.0,12.4,1.3,0.0,0.9,0.0,0.0,0.5
73054,"Census Tract 16.03, Natrona County, Wyoming",3724,41.6,42.1,41.3,2503,492,60,147,467,...,3724,334100,83.3,7.2,0.0,1.2,2.6,0.0,0.0,5.7
73055,"Census Tract 9651, Park County, Wyoming",5287,48.2,48.9,45.6,3845,968,203,263,625,...,5287,299900,93.8,4.2,0.0,0.0,0.3,0.0,0.0,1.7

In [5]:
data.columns

Index(['NAME', 'B01003_001E', 'B01002_001E', 'B01002_002E', 'B01002_003E',
       'B15003_001E', 'B15003_017E', 'B15003_018E', 'B15003_019E',
       'B15003_020E', 'B15003_021E', 'B15003_022E', 'B15003_023E',
       'B15003_024E', 'B15003_025E', 'B28002_001E', 'B28002_002E',
       'B28002_003E', 'B28002_004E', 'B28002_005E', 'B28002_006E',
       'B28002_007E', 'B28002_008E', 'B28002_009E', 'B28002_010E',
       'B28002_011E', 'B28002_012E', 'B28002_013E', 'B28003_001E',
       'B28003_002E', 'B28003_003E', 'B28003_004E', 'B28003_005E',
       'B28003_006E', 'state', 'county', 'tract', 'S2301_C03_001E',
       'S1701_C02_001E', 'S1701_C01_001E', 'S1901_C01_012E', 'S1101_C01_001E',
       'S1101_C01_002E', 'S1101_C01_004E', 'S2701_C03_011E', 'S2701_C03_012E',
       'S2701_C03_013E', 'DP04_0142PE', 'DP04_0141PE', 'DP05_0001E',
       'DP04_0089E', 'DP05_0077PE', 'DP05_0071PE', 'DP05_0078PE',
       'DP05_0079PE', 'DP05_0080PE', 'DP05_0081PE', 'DP05_0082PE',
       'DP05_0083PE'],
      dtype='object')

In [6]:
## Need to replace negative census values with NAs

data = data.replace(-1, np.nan)
data = data.replace(-1.0, np.nan)
data = data.replace( -666666666, np.nan)

In [7]:
data[data.DP04_0142PE == -666666666]

Empty DataFrame
Columns: [NAME, B01003_001E, B01002_001E, B01002_002E, B01002_003E, B15003_001E, B15003_017E, B15003_018E, B15003_019E, B15003_020E, B15003_021E, B15003_022E, B15003_023E, B15003_024E, B15003_025E, B28002_001E, B28002_002E, B28002_003E, B28002_004E, B28002_005E, B28002_006E, B28002_007E, B28002_008E, B28002_009E, B28002_010E, B28002_011E, B28002_012E, B28002_013E, B28003_001E, B28003_002E, B28003_003E, B28003_004E, B28003_005E, B28003_006E, state, county, tract, S2301_C03_001E, S1701_C02_001E, S1701_C01_001E, S1901_C01_012E, S1101_C01_001E, S1101_C01_002E, S1101_C01_004E, S2701_C03_011E, S2701_C03_012E, S2701_C03_013E, DP04_0142PE, DP04_0141PE, DP05_0001E, DP04_0089E, DP05_0077PE, DP05_0071PE, DP05_0078PE, DP05_0079PE, DP05_0080PE, DP05_0081PE, DP05_0082PE, DP05_0083PE]
Index: []

[0 rows x 59 columns]

## Which columns are more null?

In [8]:
data[data["B01003_001E"].isna()]

Empty DataFrame
Columns: [NAME, B01003_001E, B01002_001E, B01002_002E, B01002_003E, B15003_001E, B15003_017E, B15003_018E, B15003_019E, B15003_020E, B15003_021E, B15003_022E, B15003_023E, B15003_024E, B15003_025E, B28002_001E, B28002_002E, B28002_003E, B28002_004E, B28002_005E, B28002_006E, B28002_007E, B28002_008E, B28002_009E, B28002_010E, B28002_011E, B28002_012E, B28002_013E, B28003_001E, B28003_002E, B28003_003E, B28003_004E, B28003_005E, B28003_006E, state, county, tract, S2301_C03_001E, S1701_C02_001E, S1701_C01_001E, S1901_C01_012E, S1101_C01_001E, S1101_C01_002E, S1101_C01_004E, S2701_C03_011E, S2701_C03_012E, S2701_C03_013E, DP04_0142PE, DP04_0141PE, DP05_0001E, DP04_0089E, DP05_0077PE, DP05_0071PE, DP05_0078PE, DP05_0079PE, DP05_0080PE, DP05_0081PE, DP05_0082PE, DP05_0083PE]
Index: []

[0 rows x 59 columns]

In [9]:
data[data["DP05_0001E"].isna()]

Empty DataFrame
Columns: [NAME, B01003_001E, B01002_001E, B01002_002E, B01002_003E, B15003_001E, B15003_017E, B15003_018E, B15003_019E, B15003_020E, B15003_021E, B15003_022E, B15003_023E, B15003_024E, B15003_025E, B28002_001E, B28002_002E, B28002_003E, B28002_004E, B28002_005E, B28002_006E, B28002_007E, B28002_008E, B28002_009E, B28002_010E, B28002_011E, B28002_012E, B28002_013E, B28003_001E, B28003_002E, B28003_003E, B28003_004E, B28003_005E, B28003_006E, state, county, tract, S2301_C03_001E, S1701_C02_001E, S1701_C01_001E, S1901_C01_012E, S1101_C01_001E, S1101_C01_002E, S1101_C01_004E, S2701_C03_011E, S2701_C03_012E, S2701_C03_013E, DP04_0142PE, DP04_0141PE, DP05_0001E, DP04_0089E, DP05_0077PE, DP05_0071PE, DP05_0078PE, DP05_0079PE, DP05_0080PE, DP05_0081PE, DP05_0082PE, DP05_0083PE]
Index: []

[0 rows x 59 columns]

In [29]:
#The missing values have very small populations
data[data.median_age_overall.isnull()].total_pop2.value_counts()

0     646
4       7
8       3
9       3
2       2
5       2
11      2
14      2
6       1
10      1
16      1
28      1
58      1
Name: total_pop2, dtype: int64

## Rename Columns

In [30]:
## Renaming data columns
data = data.rename(columns = {"B01002_001E" : "median_age_overall", "B01002_002E": "median_age_male", "B01002_003E" : 
                      "median_age_female", "DP05_0001E" : "total_population", "B01003_001E" : "total_pop2",
                              "DP04_0089E" : "median_house_value",
                      "S1901_C01_012E" : "median_income", "S2301_C03_001E" : "employment_rate",
                      "S1101_C01_002E": "ave_household_size", "S1101_C01_004E" : "ave_family_size", "S1101_C01_001E" :
                             "total_households"})

## Calculating Additional Data Columns

In [31]:
np.sum(data["DP04_0142PE"]<0)

0

In [50]:
def safe_division(x, y):
    try:
        return (x / y)*100
    except:
        #y would have been 0 so return NAN
        return np.nan

In [33]:
## Calculating Additional Data Columns
data["pct_rent_burdened"] = data.apply(lambda x:  x["DP04_0142PE"] + x["DP04_0141PE"], axis=1)
data["poverty_rate"] = data.apply(lambda x: safe_division(x["S1701_C02_001E"], x["S1701_C01_001E"]), axis=1)
data["pct_pop_bachelors+"] = data.apply(lambda x: safe_division((x["B15003_022E"] + x["B15003_023E"] + x["B15003_024E"] +
                                                 x["B15003_025E"]), x["B15003_001E"]), axis=1)
data["pct_pop_hs+"] = data.apply(lambda x: x["pct_pop_bachelors+"] + safe_division(( x["B15003_018E"] + x["B15003_019E"] + 
                                            x["B15003_020E"] + x["B15003_021E"]), x["B15003_001E"]), axis=1)

## Internet Statistics
data["pct_internet"] = data.apply(lambda x: safe_division(x["B28002_002E"] , x["B28002_001E"]), axis=1)
data["pct_internet_dial_up"]= data.apply(lambda x: safe_division(x["B28002_003E"] , x["B28002_001E"]), axis=1)
data["pct_internet_broadband_any_type"]= data.apply(lambda x: safe_division(x["B28002_004E"] , x["B28002_001E"]), axis=1)
data["pct_internet_cellular"]= data.apply(lambda x: safe_division(x["B28002_005E"] , x["B28002_001E"]), axis=1)
data["pct_only_cellular"]= data.apply(lambda x: safe_division(x["B28002_006E"] , x["B28002_001E"]), axis=1)
data["pct_internet_broadband_fiber"]= data.apply(lambda x: safe_division(x["B28002_008E"] , x["B28002_001E"]), axis=1)
data["pct_internet_broadband_satellite"]= data.apply(lambda x: safe_division(x["B28002_009E"] , x["B28002_001E"]), axis=1)
data["pct_internet_only_satellite"]= data.apply(lambda x: safe_division(x["B28002_010E"] , x["B28002_001E"]), axis=1)
data["pct_internet_other"]= data.apply(lambda x: safe_division(x["B28002_011E"] , x["B28002_001E"]), axis=1)
data["pct_internet_no_subscrp"]= data.apply(lambda x: safe_division(x["B28002_012E"] , x["B28002_001E"]), axis=1)
data["pct_internet_none"]= data.apply(lambda x: safe_division(x["B28002_013E"] , x["B28002_001E"]), axis=1)


## Computer Statistics
data["pct_computer"] = data.apply(lambda x: safe_division(x["B28003_002E"] , x["B28003_001E"]), axis=1)
data["pct_computer_with_dialup"] = data.apply(lambda x: safe_division(x["B28003_003E"] , x["B28003_001E"]), axis=1)
data["pct_computer_with_broadband"] = data.apply(lambda x: safe_division(x["B28003_004E"] , x["B28003_001E"]), axis=1)
data["pct_computer_no_internet"] = data.apply(lambda x: safe_division(x["B28003_005E"] , x["B28003_001E"]), axis=1)
data["pct_no_computer"] = data.apply(lambda x: safe_division(x["B28003_006E"] , x["B28003_001E"]), axis=1)

In [34]:
## Race/Ethnicity Statistics To Rename

data = data.rename(columns = {"DP05_0077PE" : "pct_white", "DP05_0071PE" : "pct_hisp_latino", "DP05_0078PE" :
                             "pct_black", "DP05_0079PE" : "pct_native", "DP05_0080PE" : "pct_asian", "DP05_0081PE" :
                             "pct_hi_pi", "DP05_0082PE" : "pct_other_race", "DP05_0083PE" : "pct_two+_race"})

In [35]:
## Health Insurance Statistics to Rename

data = data.rename(columns = {"S2701_C03_011E" : "pct_health_ins_children", "S2701_C03_012E" :
                              "pct_health_ins_19_64", "S2701_C03_013E" : "pct_health_ins_65+"
    
})

In [36]:
cols_to_drop = []
for col in data.columns:
    if col.startswith("DP"):
        cols_to_drop.append(col)
    elif col.startswith("B"):
        cols_to_drop.append(col)
    elif col.startswith("S"):
        cols_to_drop.append(col)
        
cols_to_drop

['B15003_001E',
 'B15003_017E',
 'B15003_018E',
 'B15003_019E',
 'B15003_020E',
 'B15003_021E',
 'B15003_022E',
 'B15003_023E',
 'B15003_024E',
 'B15003_025E',
 'B28002_001E',
 'B28002_002E',
 'B28002_003E',
 'B28002_004E',
 'B28002_005E',
 'B28002_006E',
 'B28002_007E',
 'B28002_008E',
 'B28002_009E',
 'B28002_010E',
 'B28002_011E',
 'B28002_012E',
 'B28002_013E',
 'B28003_001E',
 'B28003_002E',
 'B28003_003E',
 'B28003_004E',
 'B28003_005E',
 'B28003_006E',
 'S1701_C02_001E',
 'S1701_C01_001E',
 'DP04_0142PE',
 'DP04_0141PE']

In [37]:
new_data = data.drop(columns=cols_to_drop)
new_data.columns

Index(['NAME', 'total_pop2', 'median_age_overall', 'median_age_male',
       'median_age_female', 'state', 'county', 'tract', 'employment_rate',
       'median_income', 'total_households', 'ave_household_size',
       'ave_family_size', 'pct_health_ins_children', 'pct_health_ins_19_64',
       'pct_health_ins_65+', 'total_population', 'median_house_value',
       'pct_white', 'pct_hisp_latino', 'pct_black', 'pct_native', 'pct_asian',
       'pct_hi_pi', 'pct_other_race', 'pct_two+_race', 'pct_rent_burdened',
       'poverty_rate', 'pct_pop_bachelors+', 'pct_pop_hs+', 'pct_internet',
       'pct_internet_dial_up', 'pct_internet_broadband_any_type',
       'pct_internet_cellular', 'pct_only_cellular',
       'pct_internet_broadband_fiber', 'pct_internet_broadband_satellite',
       'pct_internet_only_satellite', 'pct_internet_other',
       'pct_internet_no_subscrp', 'pct_internet_none', 'pct_computer',
       'pct_computer_with_dialup', 'pct_computer_with_broadband',
       'pct_computer_no_internet', 'pct_no_computer'],
      dtype='object')

In [38]:
new_data.to_csv("../data/relabeled_census.csv",index=False)

## Data Cleaning Part 2
On additional data colleced on 2/22

In [2]:
data = pd.read_csv("../data/additional_census_data_2_22.csv")
data

,NAME,B15003_001E,B15003_015E,B15003_016E,B15003_017E,B15003_018E,B15003_019E,B15003_020E,B15003_021E,B15003_022E,...,S1810_C01_001E,S1810_C01_019E,S1810_C01_029E,S1810_C01_039E,S1810_C01_047E,S1810_C01_055E,S1810_C01_063E,S1810_C02_001E,S1101_C01_010E,S1101_C01_009E
0,"Census Tract 11, Jefferson County, Alabama",3285.0,23.0,47.0,552.0,201.0,269.0,534.0,362.0,813.0,...,4655.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,842.0,37.3,1851.0
1,"Census Tract 14, Jefferson County, Alabama",1274.0,82.0,36.0,300.0,15.0,57.0,399.0,63.0,130.0,...,1946.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,426.0,16.5,816.0
2,"Census Tract 20, Jefferson County, Alabama",2802.0,219.0,92.0,720.0,134.0,267.0,571.0,199.0,192.0,...,4007.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,851.0,30.4,1419.0
3,"Census Tract 38.02, Jefferson County, Alabama",3464.0,119.0,139.0,1294.0,32.0,221.0,551.0,585.0,275.0,...,5291.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,952.0,34.7,1894.0
4,"Census Tract 40, Jefferson County, Alabama",1971.0,81.0,56.0,540.0,144.0,130.0,509.0,117.0,107.0,...,2533.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,-888888888.0,966.0,11.9,1429.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73051,"Census Tract 215, Hillsborough County, New Ham...",3728.0,42.0,36.0,967.0,183.0,196.0,504.0,360.0,802.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73052,"Census Tract 1.02, Hillsborough County, New Ha...",3335.0,8.0,9.0,408.0,79.0,177.0,406.0,267.0,1185.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73053,"Census Tract 14, Hillsborough County, New Hamp...",1514.0,91.0,0.0,446.0,83.0,96.0,209.0,104.0,152.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73054,"Census Tract 106, Hillsborough County, New Ham...",3817.0,89.0,53.0,1000.0,326.0,286.0,722.0,367.0,525.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73055,"Census Tract 114.02, Hillsborough County, New ...",3553.0,17.0,15.0,1002.0,99.0,231.0,284.0,262.0,981.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
np.unique(data.state).shape

(51,)

In [7]:
data.isnull().sum()

NAME                  0
B15003_001E       10137
B15003_015E       10137
B15003_016E       10137
B15003_017E       10137
                  ...
S1810_C01_055E      295
S1810_C01_063E      295
S1810_C02_001E      295
S1101_C01_010E      295
S1101_C01_009E      295
Length: 66, dtype: int64

In [8]:
data[data.B15003_001E.isna()].state.value_counts()

34    2010
4     1526
18    1511
25    1478
24    1406
32     687
54     484
15     351
44     244
46     222
10     218
Name: state, dtype: int64

In [9]:
data[data.S1810_C01_055E.isna()].state.value_counts()

33    295
Name: state, dtype: int64

In [17]:
data3 = pd.read_csv("../data/additional_data_v3.csv")
data3.head()

,NAME,B15003_001E,B15003_015E,B15003_016E,B15003_017E,B15003_018E,B15003_019E,B15003_020E,B15003_021E,B15003_022E,...,S1810_C01_001E,S1810_C01_019E,S1810_C01_029E,S1810_C01_039E,S1810_C01_047E,S1810_C01_055E,S1810_C01_063E,S1810_C02_001E,S1101_C01_010E,S1101_C01_009E
0,"Census Tract 5012.10, Gloucester County, New J...",2417,26,36,579,97,138,327,224,579,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Census Tract 5013.01, Gloucester County, New J...",2490,9,28,435,89,210,439,291,670,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Census Tract 5013.03, Gloucester County, New J...",1843,45,12,458,30,53,237,282,392,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Census Tract 5019, Gloucester County, New Jersey",2990,70,134,712,187,255,392,366,473,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Census Tract 5003, Gloucester County, New Jersey",2052,32,34,771,117,180,301,174,238,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
data3.state.value_counts()

34    2010
18    1511
54     484
15     351
46     222
Name: state, dtype: int64

In [24]:
data3[data3.B15003_001E.isna()].state.value_counts()

Series([], Name: state, dtype: int64)

In [27]:
data3[data3.S1810_C01_055E.isna()].state.value_counts()

34    2010
Name: state, dtype: int64

In [19]:
data2 = pd.read_csv("../data/additional_data_v2.csv")
data2.state.value_counts()

34    2010
25    1478
24    1406
32     687
15     351
33     295
10     218
Name: state, dtype: int64

In [25]:
data2[data2.B15003_001E.isna()].state.value_counts()

15    351
Name: state, dtype: int64

In [28]:
data2[data2.S1810_C01_055E.isna()].state.value_counts()

34    2010
10     218
Name: state, dtype: int64

In [20]:
data4 = pd.read_csv("../data/additional_data_v4.csv")
data4.state.value_counts()

34    2010
4     1526
44     244
10     218
Name: state, dtype: int64

In [26]:
data4[data4.B15003_001E.isna()].state.value_counts()

Series([], Name: state, dtype: int64)

In [29]:
data4[data4.S1810_C01_055E.isna()].state.value_counts()

Series([], Name: state, dtype: int64)

In [30]:
#Filter to just rows where state is not 34, 4, 44, 10
new_data = data[data.state!=4]
new_data = new_data[new_data.state!=34]
new_data = new_data[new_data.state!=44]
new_data = new_data[new_data.state!=10]

In [31]:
big_data = pd.concat([new_data, data4], ignore_index=True)

In [32]:
big_data[big_data.B15003_001E.isna()].state.value_counts()

18    1511
25    1478
24    1406
32     687
54     484
15     351
46     222
Name: state, dtype: int64

In [33]:
#Now drop other missing rows
big_data = big_data[big_data.state!=18]
big_data = big_data[big_data.state!=54]
big_data = big_data[big_data.state!=46]
big_data = big_data[big_data.state!=15]

#And drop 34 from data3 since got from data4
data3 = data3[data3.state!=34]

In [34]:
big_data = pd.concat([big_data, data3], ignore_index=True)

In [35]:
big_data[big_data.B15003_001E.isna()].state.value_counts()

25    1478
24    1406
32     687
Name: state, dtype: int64

In [36]:
big_data[big_data.S1810_C01_055E.isna()].state.value_counts()

33    295
Name: state, dtype: int64

In [37]:
#Now drop other missing rows
big_data = big_data[big_data.state!=25]
big_data = big_data[big_data.state!=24]
big_data = big_data[big_data.state!=32]
big_data = big_data[big_data.state!=33]

#And only take these from data2
these = [25, 24, 32, 33]
data2 = data2[data2.state.isin(these)]

big_data = pd.concat([big_data, data2], ignore_index=True)

In [38]:
big_data[big_data.B15003_001E.isna()].state.value_counts()

Series([], Name: state, dtype: int64)

In [39]:
big_data[big_data.S1810_C01_055E.isna()].state.value_counts()

Series([], Name: state, dtype: int64)

In [40]:
np.unique(big_data.state).shape

(51,)

In [44]:

pd.set_option('display.max_rows', None)
big_data.isnull().sum()

NAME                  0
B15003_001E           0
B15003_015E           0
B15003_016E           0
B15003_017E           0
B15003_018E           0
B15003_019E           0
B15003_020E           0
B15003_021E           0
B15003_022E           0
B15003_023E           0
B15003_024E           0
B15003_025E           0
B05004_001E         672
B05004_007E        6024
B09010_001E           0
B09010_002E           0
B19001_001E           0
B19001_002E           0
B19001_003E           0
B19001_004E           0
B19001_005E           0
B19001_006E           0
B19001_007E           0
B19001_008E           0
B19001_009E           0
B19001_010E           0
B19001_011E           0
B19001_012E           0
B19001_013E           0
B19001_014E           0
B19001_015E           0
B19001_016E           0
B19001_017E           0
state                 0
county                0
tract                 0
S0101_C01_001E        0
S0101_C01_002E        0
S0101_C01_003E        0
S0101_C01_004E        0
S0101_C01_005E        0
S0101_C01_006E        0
S0101_C01_007E        0
S0101_C01_008E        0
S0101_C01_009E        0
S0101_C01_010E        0
S0101_C01_011E        0
S0101_C01_012E        0
S0101_C01_013E        0
S0101_C01_014E        0
S0101_C01_015E        0
S0101_C01_016E        0
S0101_C01_017E        0
S0101_C01_018E        0
S0101_C01_019E        0
S1810_C01_001E        0
S1810_C01_019E    73056
S1810_C01_029E    73056
S1810_C01_039E    73056
S1810_C01_047E    73056
S1810_C01_055E    73056
S1810_C01_063E    73056
S1810_C02_001E        0
S1101_C01_010E      829
S1101_C01_009E        0
dtype: int64

In [42]:
big_data = big_data.replace(-1, np.nan)
big_data = big_data.replace(-666666666, np.nan)
big_data = big_data.replace(-888888888, np.nan)
big_data = big_data.replace(-666666666.0, np.nan)

In [46]:
big_data.to_csv("../data/aggregated_census_2_22.csv", index_label=False)

## DATA cleaning Part 2

In [47]:
big_data = pd.read_csv("../data/aggregated_census_2_22.csv")

In [48]:
big_data.head()

,NAME,B15003_001E,B15003_015E,B15003_016E,B15003_017E,B15003_018E,B15003_019E,B15003_020E,B15003_021E,B15003_022E,...,S1810_C01_001E,S1810_C01_019E,S1810_C01_029E,S1810_C01_039E,S1810_C01_047E,S1810_C01_055E,S1810_C01_063E,S1810_C02_001E,S1101_C01_010E,S1101_C01_009E
0,"Census Tract 11, Jefferson County, Alabama",3285.0,23.0,47.0,552.0,201.0,269.0,534.0,362.0,813.0,...,4655.0,NaN,NaN,NaN,NaN,NaN,NaN,842.0,37.3,1851.0
1,"Census Tract 14, Jefferson County, Alabama",1274.0,82.0,36.0,300.0,15.0,57.0,399.0,63.0,130.0,...,1946.0,NaN,NaN,NaN,NaN,NaN,NaN,426.0,16.5,816.0
2,"Census Tract 20, Jefferson County, Alabama",2802.0,219.0,92.0,720.0,134.0,267.0,571.0,199.0,192.0,...,4007.0,NaN,NaN,NaN,NaN,NaN,NaN,851.0,30.4,1419.0
3,"Census Tract 38.02, Jefferson County, Alabama",3464.0,119.0,139.0,1294.0,32.0,221.0,551.0,585.0,275.0,...,5291.0,NaN,NaN,NaN,NaN,NaN,NaN,952.0,34.7,1894.0
4,"Census Tract 40, Jefferson County, Alabama",1971.0,81.0,56.0,540.0,144.0,130.0,509.0,117.0,107.0,...,2533.0,NaN,NaN,NaN,NaN,NaN,NaN,966.0,11.9,1429.0

In [49]:
big_data.columns

Index(['NAME', 'B15003_001E', 'B15003_015E', 'B15003_016E', 'B15003_017E',
       'B15003_018E', 'B15003_019E', 'B15003_020E', 'B15003_021E',
       'B15003_022E', 'B15003_023E', 'B15003_024E', 'B15003_025E',
       'B05004_001E', 'B05004_007E', 'B09010_001E', 'B09010_002E',
       'B19001_001E', 'B19001_002E', 'B19001_003E', 'B19001_004E',
       'B19001_005E', 'B19001_006E', 'B19001_007E', 'B19001_008E',
       'B19001_009E', 'B19001_010E', 'B19001_011E', 'B19001_012E',
       'B19001_013E', 'B19001_014E', 'B19001_015E', 'B19001_016E',
       'B19001_017E', 'state', 'county', 'tract', 'S0101_C01_001E',
       'S0101_C01_002E', 'S0101_C01_003E', 'S0101_C01_004E', 'S0101_C01_005E',
       'S0101_C01_006E', 'S0101_C01_007E', 'S0101_C01_008E', 'S0101_C01_009E',
       'S0101_C01_010E', 'S0101_C01_011E', 'S0101_C01_012E', 'S0101_C01_013E',
       'S0101_C01_014E', 'S0101_C01_015E', 'S0101_C01_016E', 'S0101_C01_017E',
       'S0101_C01_018E', 'S0101_C01_019E', 'S1810_C01_001E', 'S1810_C01_019E',
       'S1810_C01_029E', 'S1810_C01_039E', 'S1810_C01_047E', 'S1810_C01_055E',
       'S1810_C01_063E', 'S1810_C02_001E', 'S1101_C01_010E', 'S1101_C01_009E'],
      dtype='object')

In [51]:
## More educational statistics
big_data["pct_pop_ged"] = big_data.apply(lambda x: safe_division((x["B15003_018E"]), x["B15003_001E"]), axis=1)
big_data["pct_pop_some_college"] = big_data.apply(lambda x: safe_division((x["B15003_019E"] + x["B15003_020E"]), x["B15003_001E"]), axis=1)
big_data["pct_pop_associates"] = big_data.apply(lambda x: safe_division((x["B15003_021E"]), x["B15003_001E"]), axis=1)


## Foreign born
big_data["pct_pop_foreign_born"] = big_data.apply(lambda x: safe_division((x["B05004_007E"]), x["B05004_001E"]), axis=1)

## RECEIPT OF SUPPLEMENTAL SECURITY INCOME (SSI), CASH PUBLIC ASSISTANCE INCOME, OR FOOD STAMPS/SNAP IN THE PAST 12 MONTHS
## BY HOUSEHOLD TYPE FOR CHILDREN UNDER 18 YEARS IN HOUSEHOLDS

big_data["pct_pop_ssi_households"] = big_data.apply(lambda x: safe_division((x["B09010_002E"]), x["B09010_001E"]), axis=1)

## Household income groups
big_data["pct_pop_lt_10k"] = big_data.apply(lambda x: safe_division((x["B19001_002E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_10k_thru_15k"] = big_data.apply(lambda x: safe_division((x["B19001_003E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_15k_thru_20k"] = big_data.apply(lambda x: safe_division((x["B19001_004E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_20k_thru_25k"] = big_data.apply(lambda x: safe_division((x["B19001_005E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_25k_thru_30k"] = big_data.apply(lambda x: safe_division((x["B19001_006E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_30k_thru_35k"] = big_data.apply(lambda x: safe_division((x["B19001_007E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_35k_thru_40k"] = big_data.apply(lambda x: safe_division((x["B19001_008E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_40k_thru_45k"] = big_data.apply(lambda x: safe_division((x["B19001_009E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_45k_thru_50k"] = big_data.apply(lambda x: safe_division((x["B19001_010E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_50k_thru_60k"] = big_data.apply(lambda x: safe_division((x["B19001_011E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_60k_thru_75k"] = big_data.apply(lambda x: safe_division((x["B19001_012E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_75k_thru_100k"] = big_data.apply(lambda x: safe_division((x["B19001_013E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_100k_thru_125k"] = big_data.apply(lambda x: safe_division((x["B19001_014E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_125k_thru_150k"] = big_data.apply(lambda x: safe_division((x["B19001_015E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_150k_thru_200k"] = big_data.apply(lambda x: safe_division((x["B19001_016E"]), x["B19001_001E"]), axis=1)
big_data["pct_pop_gt_200k"] = big_data.apply(lambda x: safe_division((x["B19001_017E"]), x["B19001_001E"]), axis=1)

In [52]:
## Age groups
big_data["pct_pop_lt_5"] = big_data.apply(lambda x: safe_division((x["S0101_C01_002E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_5_to_9"] = big_data.apply(lambda x: safe_division((x["S0101_C01_003E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_10_to_14"] = big_data.apply(lambda x: safe_division((x["S0101_C01_004E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_15_to_19"] = big_data.apply(lambda x: safe_division((x["S0101_C01_005E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_20_to_24"] = big_data.apply(lambda x: safe_division((x["S0101_C01_006E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_25_to_29"] = big_data.apply(lambda x: safe_division((x["S0101_C01_007E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_30_to_34"] = big_data.apply(lambda x: safe_division((x["S0101_C01_008E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_35_to_39"] = big_data.apply(lambda x: safe_division((x["S0101_C01_009E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_40_to_44"] = big_data.apply(lambda x: safe_division((x["S0101_C01_010E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_45_to_49"] = big_data.apply(lambda x: safe_division((x["S0101_C01_011E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_50_to_54"] = big_data.apply(lambda x: safe_division((x["S0101_C01_012E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_55_to_59"] = big_data.apply(lambda x: safe_division((x["S0101_C01_013E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_60_to_64"] = big_data.apply(lambda x: safe_division((x["S0101_C01_014E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_65_to_69"] = big_data.apply(lambda x: safe_division((x["S0101_C01_015E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_70_to_74"] = big_data.apply(lambda x: safe_division((x["S0101_C01_016E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_75_to_79"] = big_data.apply(lambda x: safe_division((x["S0101_C01_017E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_80_to_84"] = big_data.apply(lambda x: safe_division((x["S0101_C01_018E"]), x["S0101_C01_001E"]), axis=1)
big_data["pct_pop_gt_85"] = big_data.apply(lambda x: safe_division((x["S0101_C01_019E"]), x["S0101_C01_001E"]), axis=1)


## Disability
big_data["pct_pop_disability"] = big_data.apply(lambda x: safe_division((x["S1810_C02_001E"]), x["S1810_C01_001E"]), axis=1)


## households with people < 18
big_data["pct_pop_households_with_kids"] = big_data.apply(lambda x: safe_division((x["S1101_C01_010E"]), x["S1101_C01_009E"]), axis=1)

In [57]:
cols_to_keep = ['state', 'tract', 'county']

for col in big_data.columns:
    if col.startswith("pct_"):
        cols_to_keep.append(col)

In [53]:
fcc = pd.read_csv("../data/fcc_census.csv")
fcc.head()

,tract_geoid,All_Provider_Count,All_Providers,MaxAdDown,MaxAdUp,AllMaxAdDown,AllMaxAdUp,Wired_Provider_Count,Satellite_Provider_Count,Fixed_Wireless_Provider_Count,...,pct_computer_with_dialup,pct_computer_with_broadband,pct_computer_no_internet,pct_no_computer,GEOID,ALAND,AWATER,ALAND_SQMI,AWATER_SQMI,population_density
0,1001020100,7,"{56004, 58757, 54694, 67056, 59349, 55262, 58623}",1000.0,50.0,"{0.0, 0.768, 1.5, 3.0, 100.0, 2.0, 6.0, 1000.0...","{0.0, 0.512, 0.128, 35.0, 3.0, 0.384, 0.768, 0...",3.0,4,0.0,...,0.00000,74.047955,7.475317,18.476728,1001020100,9817813,28435,3.791,0.011,52571.880770
1,1001020200,10,"{56004, 58757, 54694, 67056, 59349, 56888, 555...",1000.0,50.0,"{0.0, 1.5, 2.0, 3.0, 100.0, 6.0, 1000.0, 10.0,...","{0.0, 0.384, 0.512, 35.0, 3.0, 0.128, 0.768, 0...",6.0,4,0.0,...,0.00000,66.860465,7.848837,25.290698,1001020200,3325680,5669,1.284,0.002,152570.093458
2,1001020300,10,"{56004, 58757, 54694, 67056, 59349, 56888, 555...",1000.0,50.0,"{0.0, 2.0, 100.0, 6.0, 1000.0, 940.0, 12.0, 18...","{0.0, 0.512, 0.768, 35.0, 3.0, 1.3, 50.0}",6.0,4,0.0,...,0.00000,78.529412,9.411765,12.058824,1001020300,5349273,9054,2.065,0.003,169830.508475
3,1001020400,8,"{56004, 58757, 54694, 67056, 59349, 55514, 552...",1000.0,50.0,"{0.0, 0.768, 1.5, 3.0, 100.0, 5.0, 6.0, 2.0, 1...","{0.0, 0.512, 0.128, 35.0, 3.0, 0.384, 0.768, 0...",4.0,4,0.0,...,0.41791,85.313433,6.865672,7.402985,1001020400,6384276,8408,2.465,0.003,157322.515213
4,1001020500,13,"{56004, 58757, 54694, 56170, 54860, 54927, 670...",1000.0,1000.0,"{0.0, 1.5, 2.0, 100.0, 6.0, 1000.0, 75.0, 940....","{0.0, 0.512, 0.128, 35.0, 3.0, 0.768, 5.0, 1.3...",9.0,4,0.0,...,0.00000,89.025206,5.688155,5.286638,1001020500,11408866,43534,4.405,0.017,240544.835414

In [58]:
cols_to_keep

['state',
 'tract',
 'county',
 'pct_pop_ged',
 'pct_pop_some_college',
 'pct_pop_associates',
 'pct_pop_foreign_born',
 'pct_pop_ssi_households',
 'pct_pop_lt_10k',
 'pct_pop_10k_thru_15k',
 'pct_pop_15k_thru_20k',
 'pct_pop_20k_thru_25k',
 'pct_pop_25k_thru_30k',
 'pct_pop_30k_thru_35k',
 'pct_pop_35k_thru_40k',
 'pct_pop_40k_thru_45k',
 'pct_pop_45k_thru_50k',
 'pct_pop_50k_thru_60k',
 'pct_pop_60k_thru_75k',
 'pct_pop_75k_thru_100k',
 'pct_pop_100k_thru_125k',
 'pct_pop_125k_thru_150k',
 'pct_pop_150k_thru_200k',
 'pct_pop_gt_200k',
 'pct_pop_lt_5',
 'pct_pop_5_to_9',
 'pct_pop_10_to_14',
 'pct_pop_15_to_19',
 'pct_pop_20_to_24',
 'pct_pop_25_to_29',
 'pct_pop_30_to_34',
 'pct_pop_35_to_39',
 'pct_pop_40_to_44',
 'pct_pop_45_to_49',
 'pct_pop_50_to_54',
 'pct_pop_55_to_59',
 'pct_pop_60_to_64',
 'pct_pop_65_to_69',
 'pct_pop_70_to_74',
 'pct_pop_75_to_79',
 'pct_pop_80_to_84',
 'pct_pop_gt_85',
 'pct_pop_disability',
 'pct_pop_households_with_kids']

In [59]:
df = fcc.merge(big_data[cols_to_keep], on = ['state', 'tract', 'county'], how='outer')

In [60]:
df.columns

Index(['tract_geoid', 'All_Provider_Count', 'All_Providers', 'MaxAdDown',
       'MaxAdUp', 'AllMaxAdDown', 'AllMaxAdUp', 'Wired_Provider_Count',
       'Satellite_Provider_Count', 'Fixed_Wireless_Provider_Count',
       ...
       'pct_pop_50_to_54', 'pct_pop_55_to_59', 'pct_pop_60_to_64',
       'pct_pop_65_to_69', 'pct_pop_70_to_74', 'pct_pop_75_to_79',
       'pct_pop_80_to_84', 'pct_pop_gt_85', 'pct_pop_disability',
       'pct_pop_households_with_kids'],
      dtype='object', length=111)

In [61]:
df.shape

(73056, 111)

In [62]:
df.isnull().sum()

tract_geoid                             0
All_Provider_Count                      0
All_Providers                           0
MaxAdDown                               0
MaxAdUp                                 0
AllMaxAdDown                            0
AllMaxAdUp                              0
Wired_Provider_Count                    0
Satellite_Provider_Count                0
Fixed_Wireless_Provider_Count           0
All_Provider_Count_25                   0
All_Provider_Count_100                  0
Fixed_Wireless_Provider_Count_25        0
Wired_Provider_Count_25                 0
Satellite_Provider_Count_25             0
Fixed_Wireless_Provider_Count_100       0
Wired_Provider_Count_100                0
Satellite_Provider_Count_100            0
NAME                                    0
total_pop2                              0
median_age_overall                    672
median_age_male                       702
median_age_female                     780
state                                   0
county                                  0
tract                                   0
employment_rate                       646
median_income                        1024
total_households                        0
ave_household_size                    857
ave_family_size                       880
pct_health_ins_children               935
pct_health_ins_19_64                  762
pct_health_ins_65+                   1038
total_population                        0
median_house_value                   1972
pct_white                             646
pct_hisp_latino                       646
pct_black                             646
pct_native                            646
pct_asian                             646
pct_hi_pi                             646
pct_other_race                        646
pct_two+_race                         646
pct_rent_burdened                     977
poverty_rate                          793
pct_pop_bachelors+                    664
pct_pop_hs+                           664
pct_internet                          829
pct_internet_dial_up                  829
pct_internet_broadband_any_type       829
pct_internet_cellular                 829
pct_only_cellular                     829
pct_internet_broadband_fiber          829
pct_internet_broadband_satellite      829
pct_internet_only_satellite           829
pct_internet_other                    829
pct_internet_no_subscrp               829
pct_internet_none                     829
pct_computer                          829
pct_computer_with_dialup              829
pct_computer_with_broadband           829
pct_computer_no_internet              829
pct_no_computer                       829
GEOID                                   0
ALAND                                   0
AWATER                                  0
ALAND_SQMI                              0
AWATER_SQMI                             0
population_density                    317
pct_pop_ged                           664
pct_pop_some_college                  664
pct_pop_associates                    664
pct_pop_foreign_born                 6024
pct_pop_ssi_households               1074
pct_pop_lt_10k                        829
pct_pop_10k_thru_15k                  829
pct_pop_15k_thru_20k                  829
pct_pop_20k_thru_25k                  829
pct_pop_25k_thru_30k                  829
pct_pop_30k_thru_35k                  829
pct_pop_35k_thru_40k                  829
pct_pop_40k_thru_45k                  829
pct_pop_45k_thru_50k                  829
pct_pop_50k_thru_60k                  829
pct_pop_60k_thru_75k                  829
pct_pop_75k_thru_100k                 829
pct_pop_100k_thru_125k                829
pct_pop_125k_thru_150k                829
pct_pop_150k_thru_200k                829
pct_pop_gt_200k                       829
pct_pop_lt_5                          646
pct_pop_5_to_9                        646
pct_pop_10_to_14                      646
pct_pop_15_to_19                      646
pct_pop_20_to_24                      646
pct_pop_25_to_29                      646
pct_pop_30_to_34                      646
pct_pop_35_to_39                      646
pct_pop_40_to_44                      646
pct_pop_45_to_49                      646
pct_pop_50_to_54                      646
pct_pop_55_to_59                      646
pct_pop_60_to_64                      646
pct_pop_65_to_69                      646
pct_pop_70_to_74                      646
pct_pop_75_to_79                      646
pct_pop_80_to_84                      646
pct_pop_gt_85                         646
pct_pop_disability                    753
pct_pop_households_with_kids          829
dtype: int64

In [65]:
nbam = pd.read_csv("../data/nbam/IBNTracts.csv")

In [66]:
nbam.shape

(73767, 17)

In [67]:
nbam.head()

,Geographic Identifier - FIPS Code,Name,State,County,Total households,Total households - Margin of Error,"Percent of Households that Have No Computer, Smartphone, or Tablet","Percent of Households that Have No Computer, Smartphone, or Tablet - Margin of Error",Percent of Households with No Internet Access,Percent of Households with No Internet Access - Margin of Error,Percent of Population whose income in the past 12 months is below poverty level,Percent of Population whose income in the past 12 months is below poverty level - Margin of Error,Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps),Form 477 All Terrestrial Broadband: Max Advertised Consumer Upload Speed (Mbps),Ookla Median Download Speed (Mbps),Ookla Median Upload Speed (Mbps),Population 2019 (FCC Estimate)
0,15001020100,Census Tract 201,Hawaii,Hawaii County,1620.0,148.0,20.9,5.415057,27.8,6.229174,20.2,5.429680,1000.0,300.0,54.721001,11.841,6211.0
1,15001020202,Census Tract 202.02,Hawaii,Hawaii County,651.0,73.0,12.1,5.518258,18.9,10.228343,13.6,8.869095,1000.0,300.0,41.548000,10.927,3021.0
2,15001020300,Census Tract 203,Hawaii,Hawaii County,1698.0,127.0,16.8,7.790436,19.0,8.240864,33.5,6.966096,1000.0,300.0,51.610001,11.233,4087.0
3,15001020400,Census Tract 204,Hawaii,Hawaii County,1300.0,131.0,18.8,8.799020,24.2,9.381719,31.1,9.558358,1000.0,300.0,107.196999,11.986,3430.0
4,15001020500,Census Tract 205,Hawaii,Hawaii County,2130.0,206.0,28.6,9.463437,29.4,9.537205,39.8,10.661597,1000.0,300.0,86.380997,11.813,6180.0

In [68]:
nbam.columns

Index(['Geographic Identifier - FIPS Code', 'Name', 'State', 'County',
       'Total households', 'Total households - Margin of Error',
       'Percent of Households that Have No Computer, Smartphone, or Tablet',
       'Percent of Households that Have No Computer, Smartphone, or Tablet - Margin of Error',
       'Percent of Households with No Internet Access',
       'Percent of Households with No Internet Access - Margin of Error',
       'Percent of Population whose income in the past 12 months is below poverty level',
       'Percent of Population whose income in the past 12 months is below poverty level - Margin of Error',
       'Form 477 All Terrestrial Broadband: Max Advertised Consumer Download Speed (Mbps)',
       'Form 477 All Terrestrial Broadband: Max Advertised Consumer Upload Speed (Mbps)',
       'Ookla Median Download Speed (Mbps)',
       'Ookla Median Upload Speed (Mbps)', 'Population 2019 (FCC Estimate)'],
      dtype='object')

In [69]:
df = df.merge(nbam[['Geographic Identifier - FIPS Code', 'Ookla Median Download Speed (Mbps)',
       'Ookla Median Upload Speed (Mbps)']], left_on = 'tract_geoid', right_on = 'Geographic Identifier - FIPS Code', how='left')

In [70]:
df.isnull().sum()

tract_geoid                              0
All_Provider_Count                       0
All_Providers                            0
MaxAdDown                                0
MaxAdUp                                  0
AllMaxAdDown                             0
AllMaxAdUp                               0
Wired_Provider_Count                     0
Satellite_Provider_Count                 0
Fixed_Wireless_Provider_Count            0
All_Provider_Count_25                    0
All_Provider_Count_100                   0
Fixed_Wireless_Provider_Count_25         0
Wired_Provider_Count_25                  0
Satellite_Provider_Count_25              0
Fixed_Wireless_Provider_Count_100        0
Wired_Provider_Count_100                 0
Satellite_Provider_Count_100             0
NAME                                     0
total_pop2                               0
median_age_overall                     672
median_age_male                        702
median_age_female                      780
state                                    0
county                                   0
tract                                    0
employment_rate                        646
median_income                         1024
total_households                         0
ave_household_size                     857
ave_family_size                        880
pct_health_ins_children                935
pct_health_ins_19_64                   762
pct_health_ins_65+                    1038
total_population                         0
median_house_value                    1972
pct_white                              646
pct_hisp_latino                        646
pct_black                              646
pct_native                             646
pct_asian                              646
pct_hi_pi                              646
pct_other_race                         646
pct_two+_race                          646
pct_rent_burdened                      977
poverty_rate                           793
pct_pop_bachelors+                     664
pct_pop_hs+                            664
pct_internet                           829
pct_internet_dial_up                   829
pct_internet_broadband_any_type        829
pct_internet_cellular                  829
pct_only_cellular                      829
pct_internet_broadband_fiber           829
pct_internet_broadband_satellite       829
pct_internet_only_satellite            829
pct_internet_other                     829
pct_internet_no_subscrp                829
pct_internet_none                      829
pct_computer                           829
pct_computer_with_dialup               829
pct_computer_with_broadband            829
pct_computer_no_internet               829
pct_no_computer                        829
GEOID                                    0
ALAND                                    0
AWATER                                   0
ALAND_SQMI                               0
AWATER_SQMI                              0
population_density                     317
pct_pop_ged                            664
pct_pop_some_college                   664
pct_pop_associates                     664
pct_pop_foreign_born                  6024
pct_pop_ssi_households                1074
pct_pop_lt_10k                         829
pct_pop_10k_thru_15k                   829
pct_pop_15k_thru_20k                   829
pct_pop_20k_thru_25k                   829
pct_pop_25k_thru_30k                   829
pct_pop_30k_thru_35k                   829
pct_pop_35k_thru_40k                   829
pct_pop_40k_thru_45k                   829
pct_pop_45k_thru_50k                   829
pct_pop_50k_thru_60k                   829
pct_pop_60k_thru_75k                   829
pct_pop_75k_thru_100k                  829
pct_pop_100k_thru_125k                 829
pct_pop_125k_thru_150k                 829
pct_pop_150k_thru_200k                 829
pct_pop_gt_200k                        829
pct_pop_lt_5                           646
pct_pop_5_to_9                         646
pct_pop_10_to_14                       646
pct_pop_15_to_19                       646
pct_pop_20_to_24                       646
pct_pop_25_to_29                       646
pct_pop_30_to_34                       646
pct_pop_35_to_39                       646
pct_pop_40_to_44                       646
pct_pop_45_to_49                       646
pct_pop_50_to_54                       646
pct_pop_55_to_59                       646
pct_pop_60_to_64                       646
pct_pop_65_to_69                       646
pct_pop_70_to_74                       646
pct_pop_75_to_79                       646
pct_pop_80_to_84                       646
pct_pop_gt_85                          646
pct_pop_disability                     753
pct_pop_households_with_kids           829
Geographic Identifier - FIPS Code      317
Ookla Median Download Speed (Mbps)     462
Ookla Median Upload Speed (Mbps)       462
dtype: int64

In [71]:
df[df['Geographic Identifier - FIPS Code'].isna()][['NAME', 'state', 'total_pop2']]

                                                    NAME  state  total_pop2
43            Census Tract 9900, Baldwin County, Alabama    1.0         0.0
868            Census Tract 9900, Mobile County, Alabama    1.0         0.0
3920       Census Tract 9900, Alameda County, California    6.0         0.0
4204   Census Tract 9900, Contra Costa County, Califo...    6.0         0.0
4212     Census Tract 9900, Del Norte County, California    6.0         0.0
4255     Census Tract 9900, El Dorado County, California    6.0         0.0
4491      Census Tract 9901, Humboldt County, California    6.0         0.0
7074   Census Tract 9901, Los Angeles County, California    6.0         0.0
7075   Census Tract 9902, Los Angeles County, California    6.0         0.0
7076   Census Tract 9903, Los Angeles County, California    6.0         0.0
7155         Census Tract 9901, Marin County, California    6.0         0.0
7182     Census Tract 9901, Mendocino County, California    6.0         0.0
7332      Census Tract 9900, Monterey County, California    6.0         0.0
7975        Census Tract 9901, Orange County, California    6.0         0.0
8060        Census Tract 9900, Placer County, California    6.0         0.0
9845     Census Tract 9901, San Diego County, California    6.0         0.0
10042  Census Tract 9901, San Francisco County, Calif...    6.0         0.0
10235  Census Tract 9900, San Luis Obispo County, Cal...    6.0         0.0
10393    Census Tract 9901, San Mateo County, California    6.0         0.0
10483  Census Tract 9900, Santa Barbara County, Calif...    6.0         0.0
10908   Census Tract 9901, Santa Cruz County, California    6.0         0.0
11167       Census Tract 9901, Sonoma County, California    6.0         0.0
11561      Census Tract 9901, Ventura County, California    6.0         0.0
13076   Census Tract 9900, Fairfield County, Connecticut    9.0         0.0
13388   Census Tract 9901, Middlesex County, Connecticut    9.0         0.0
13578   Census Tract 9900, New Haven County, Connecticut    9.0         0.0
13644  Census Tract 9901, New London County, Connecticut    9.0         0.0
13731           Census Tract 9900, Kent County, Delaware   10.0         0.0
13862     Census Tract 9901, New Castle County, Delaware   10.0         0.0
13916         Census Tract 9900, Sussex County, Delaware   10.0         0.0
14199             Census Tract 9900, Bay County, Florida   12.0         0.0
14317         Census Tract 9900, Brevard County, Florida   12.0         0.0
14679         Census Tract 9900, Broward County, Florida   12.0         0.0
14721       Census Tract 9900, Charlotte County, Florida   12.0         0.0
14749          Census Tract 9900, Citrus County, Florida   12.0         0.0
14853         Census Tract 9900, Collier County, Florida   12.0         0.0
14878           Census Tract 9900, Dixie County, Florida   12.0         0.0
15052           Census Tract 9900, Duval County, Florida   12.0         0.0
15124        Census Tract 9900, Escambia County, Florida   12.0         0.0
15145         Census Tract 9900, Flagler County, Florida   12.0         0.0
15150        Census Tract 9900, Franklin County, Florida   12.0         0.0
15151        Census Tract 9901, Franklin County, Florida   12.0         0.0
15169          Census Tract 9900, Glades County, Florida   12.0         0.0
15173            Census Tract 9900, Gulf County, Florida   12.0         0.0
15189          Census Tract 9900, Hendry County, Florida   12.0         0.0
15234        Census Tract 9900, Hernando County, Florida   12.0         0.0
15581    Census Tract 9900, Hillsborough County, Florida   12.0         0.0
15582    Census Tract 9901, Hillsborough County, Florida   12.0         0.0
15617    Census Tract 9900, Indian River County, Florida   12.0         0.0
15632       Census Tract 9900, Jefferson County, Florida   12.0         0.0
15857             Census Tract 9900, Lee County, Florida   12.0         0.0
15935            Census Tract 9900, Levy County, Florida   12.0         0.0
16021         Census Tract 9900, Manatee County, Florida   12.0         0.0
16119          Census Tract 9900, Martin County, Florida   12.0         0.0
16120          Census Tract 9901, Martin County, Florida   12.0         0.0
16639      Census Tract 9900, Miami-Dade County, Florida   12.0         0.0
16670          Census Tract 9900, Monroe County, Florida   12.0         0.0
16683          Census Tract 9900, Nassau County, Florida   12.0         0.0
16725        Census Tract 9901, Okaloosa County, Florida   12.0         0.0
16726        Census Tract 9902, Okaloosa County, Florida   12.0         0.0
16738      Census Tract 9900, Okeechobee County, Florida   12.0         0.0
16945          Census Tract 9900, Orange County, Florida   12.0         0.0
17323      Census Tract 9900, Palm Beach County, Florida   12.0         0.0
17324      Census Tract 9901, Palm Beach County, Florida   12.0         0.0
17458           Census Tract 9900, Pasco County, Florida   12.0         0.0
17703        Census Tract 9900, Pinellas County, Florida   12.0         0.0
17704        Census Tract 9901, Pinellas County, Florida   12.0         0.0
17915       Census Tract 9901, St. Johns County, Florida   12.0         0.0
17916       Census Tract 9902, St. Johns County, Florida   12.0         0.0
17961       Census Tract 9900, St. Lucie County, Florida   12.0         0.0
17987      Census Tract 9900, Santa Rosa County, Florida   12.0         0.0
18082        Census Tract 9900, Sarasota County, Florida   12.0         0.0
18199          Census Tract 9900, Taylor County, Florida   12.0         0.0
18316         Census Tract 9900, Volusia County, Florida   12.0         0.0
18321         Census Tract 9900, Wakulla County, Florida   12.0         0.0
18333          Census Tract 9900, Walton County, Florida   12.0         0.0
18506          Census Tract 9900, Camden County, Georgia   13.0         0.0
18611         Census Tract 9900, Chatham County, Georgia   13.0         0.0
19490           Census Tract 9900, Glynn County, Georgia   13.0         0.0
19809         Census Tract 9900, Liberty County, Georgia   13.0         0.0
19853        Census Tract 9900, McIntosh County, Georgia   13.0         0.0
20343           Census Tract 9900, Hawaii County, Hawaii   15.0         0.0
20344           Census Tract 9901, Hawaii County, Hawaii   15.0         0.0
20345           Census Tract 9903, Hawaii County, Hawaii   15.0         0.0
20346           Census Tract 9904, Hawaii County, Hawaii   15.0         0.0
20347           Census Tract 9905, Hawaii County, Hawaii   15.0         0.0
20348           Census Tract 9906, Hawaii County, Hawaii   15.0         0.0
20349           Census Tract 9907, Hawaii County, Hawaii   15.0         0.0
20350           Census Tract 9908, Hawaii County, Hawaii   15.0         0.0
20351           Census Tract 9909, Hawaii County, Hawaii   15.0         0.0
20352           Census Tract 9910, Hawaii County, Hawaii   15.0         0.0
20353           Census Tract 9911, Hawaii County, Hawaii   15.0         0.0
20354           Census Tract 9912, Hawaii County, Hawaii   15.0         0.0
20355           Census Tract 9913, Hawaii County, Hawaii   15.0         0.0
20356           Census Tract 9914, Hawaii County, Hawaii   15.0         0.0
20357           Census Tract 9915, Hawaii County, Hawaii   15.0         0.0
20358           Census Tract 9916, Hawaii County, Hawaii   15.0         0.0
20359           Census Tract 9917, Hawaii County, Hawaii   15.0         0.0
20603      Census Tract 9900.01, Honolulu County, Hawaii   15.0         0.0
20605          Census Tract 9900, Kalawao County, Hawaii   15.0         0.0
20620            Census Tract 9901, Kauai County, Hawaii   15.0         0.0
20621            Census Tract 9902, Kauai County, Hawaii   15.0         0.0
20622            Census Tract 9903, Kauai County, Hawaii   15.0         0.0
20658             Census Tract 9900, Maui County, Hawaii   15.0         0.0
20659             Census Tract 9902, Maui County, Hawaii   15.0         0.0
20660             Census Tract 9912, Maui County, Hawaii   15.0         0.0
22416           Census Tract 9900, Cook County, Illinois   17.0         0.0
23113           Census Tract 9900, Lake County, Illinois   17.0         0.0
24794            Census Tract 9900, Lake County, Indiana   18.0         0.0
24823         Census Tract 9900, LaPorte County, Indiana   18.0         0.0
25245          Census Tract 9900, Porter County, Indiana   18.0         0.0
28496       Census Tract 9900, Cameron Parish, Louisiana   22.0         0.0
28651        Census Tract 9900, Iberia Parish, Louisiana   22.0         0.0
28789     Census Tract 9900, Jefferson Parish, Louisiana   22.0         0.0
28790     Census Tract 9901, Jefferson Parish, Louisiana   22.0         0.0
28864     Census Tract 9900, Lafourche Parish, Louisiana   22.0         0.0
29093       Census Tract 9900, Orleans Parish, Louisiana   22.0         0.0
29142   Census Tract 9900, Plaquemines Parish, Louisiana   22.0         0.0
29214   Census Tract 9900, St. Bernard Parish, Louisiana   22.0         0.0
29294      Census Tract 9900, St. Mary Parish, Louisiana   22.0         0.0
29337   Census Tract 9900, St. Tammany Parish, Louisiana   22.0         0.0
29382    Census Tract 9900, Terrebonne Parish, Louisiana   22.0         0.0
29401     Census Tract 9900, Vermilion Parish, Louisiana   22.0         0.0
29569        Census Tract 9900, Cumberland County, Maine   23.0         0.0
29596           Census Tract 9900, Hancock County, Maine   23.0         0.0
29638              Census Tract 9900, Knox County, Maine   23.0         0.0
29648           Census Tract 9900, Lincoln County, Maine   23.0         0.0
29728         Census Tract 9900, Sagadahoc County, Maine   23.0         0.0
29767        Census Tract 9900, Washington County, Maine   23.0         0.0
29808              Census Tract 9901, York County, Maine   23.0         0.0
29936   Census Tract 9900, Anne Arundel County, Maryland   24.0         0.0
30169        Census Tract 9901, Calvert County, Maryland   24.0         0.0
30266        Census Tract 9900, Charles County, Maryland   24.0         0.0
30276     Census Tract 9900, Dorchester County, Maryland   24.0         0.0
30462           Census Tract 9900, Kent County, Maryland   24.0         0.0
30907   Census Tract 9900, Queen Anne's County, Maryland   24.0         0.0
30908   Census Tract 9901, Queen Anne's County, Maryland   24.0         0.0
30909   Census Tract 9902, Queen Anne's County, Maryland   24.0         0.0
30927     Census Tract 9900, St. Mary's County, Maryland   24.0         0.0
30935       Census Tract 9901, Somerset County, Maryland   24.0         0.0
30946         Census Tract 9900, Talbot County, Maryland   24.0         0.0
31014      Census Tract 9900, Worcester County, Maryland   24.0         0.0
31271  Census Tract 9900, Barnstable County, Massachu...   25.0         0.0
31436   Census Tract 9900, Bristol County, Massachusetts   25.0         0.0
31441     Census Tract 9900, Dukes County, Massachusetts   25.0         0.0
31604     Census Tract 9901, Essex County, Massachusetts   25.0         0.0
32085  Census Tract 9900, Nantucket County, Massachus...   25.0         0.0
32316  Census Tract 9900.03, Plymouth County, Massach...   25.0         0.0
32520  Census Tract 9901.01, Suffolk County, Massachu...   25.0        67.0
32698         Census Tract 9900, Alcona County, Michigan   26.0         0.0
32702          Census Tract 9900, Alger County, Michigan   26.0         0.0
32727        Census Tract 9900, Allegan County, Michigan   26.0         0.0
32737         Census Tract 9900, Alpena County, Michigan   26.0         0.0
32745         Census Tract 9900, Antrim County, Michigan   26.0         0.0
32751         Census Tract 9900, Arenac County, Michigan   26.0         0.0
32752         Census Tract 9901, Arenac County, Michigan   26.0         0.0
32755         Census Tract 9901, Baraga County, Michigan   26.0         0.0
32793            Census Tract 9900, Bay County, Michigan   26.0         0.0
32799         Census Tract 9900, Benzie County, Michigan   26.0         0.0
32848        Census Tract 9900, Berrien County, Michigan   26.0         0.0
32924     Census Tract 9900, Charlevoix County, Michigan   26.0         0.0
32933      Census Tract 9900, Cheboygan County, Michigan   26.0         0.0
32948       Census Tract 9900, Chippewa County, Michigan   26.0         0.0
32949       Census Tract 9901, Chippewa County, Michigan   26.0         0.0
32999          Census Tract 9900, Delta County, Michigan   26.0         0.0
33000          Census Tract 9901, Delta County, Michigan   26.0         0.0
33044          Census Tract 9900, Emmet County, Michigan   26.0         0.0
33192        Census Tract 9900, Gogebic County, Michigan   26.0         0.0
33209  Census Tract 9900, Grand Traverse County, Mich...   26.0         0.0
33242       Census Tract 9900, Houghton County, Michigan   26.0         0.0
33243       Census Tract 9901, Houghton County, Michigan   26.0         0.0
33256          Census Tract 9900, Huron County, Michigan   26.0         0.0
33360          Census Tract 9900, Iosco County, Michigan   26.0         0.0
33611       Census Tract 9901, Keweenaw County, Michigan   26.0         0.0
33646       Census Tract 9900, Leelanau County, Michigan   26.0         0.0
33734           Census Tract 9900, Luce County, Michigan   26.0         0.0
33740       Census Tract 9900, Mackinac County, Michigan   26.0         0.0
33957         Census Tract 9901, Macomb County, Michigan   26.0         0.0
33967       Census Tract 9900, Manistee County, Michigan   26.0         0.0
33992      Census Tract 9900, Marquette County, Michigan   26.0         0.0
34001          Census Tract 9900, Mason County, Michigan   26.0         0.0
34020      Census Tract 9900, Menominee County, Michigan   26.0         0.0
34082         Census Tract 9900, Monroe County, Michigan   26.0         0.0
34143       Census Tract 9900, Muskegon County, Michigan   26.0         0.0
34500         Census Tract 9900, Oceana County, Michigan   26.0         0.0
34511      Census Tract 9901, Ontonagon County, Michigan   26.0         0.0
34582         Census Tract 9900, Ottawa County, Michigan   26.0         0.0
34589   Census Tract 9900, Presque Isle County, Michigan   26.0         0.0
34705      Census Tract 9900, St. Clair County, Michigan   26.0         0.0
34735        Census Tract 9900, Sanilac County, Michigan   26.0         0.0
34739    Census Tract 9900, Schoolcraft County, Michigan   26.0         0.0
34770        Census Tract 9900, Tuscola County, Michigan   26.0         0.0
34786      Census Tract 9900, Van Buren County, Michigan   26.0         0.0
35496          Census Tract 9901, Wayne County, Michigan   26.0         0.0
35497          Census Tract 9902, Wayne County, Michigan   26.0         0.0
35719          Census Tract 9900, Cook County, Minnesota   27.0         0.0
36245          Census Tract 9901, Lake County, Minnesota   27.0         0.0
36653     Census Tract 9901, St. Louis County, Minnesota   27.0         0.0
36993     Census Tract 9900, Hancock County, Mississippi   28.0         0.0
37039    Census Tract 9900, Harrison County, Mississippi   28.0         0.0
37146     Census Tract 9900, Jackson County, Mississippi   28.0         0.0
40214          Census Tract 9900, Douglas County, Nevada   32.0         0.0
40372           Census Tract 9900, Washoe County, Nevada   32.0         0.0
40373           Census Tract 9901, Washoe County, Nevada   32.0         0.0
40390             Census Tract 9900, Carson City, Nevada   32.0         0.0
40650  Census Tract 9900, Rockingham County, New Hamp...   33.0         0.0
40755     Census Tract 9900, Atlantic County, New Jersey   34.0         0.0
41208     Census Tract 9901, Cape May County, New Jersey   34.0         0.0
41243   Census Tract 9900, Cumberland County, New Jersey   34.0         0.0
42104     Census Tract 9900, Monmouth County, New Jersey   34.0         0.0
42330        Census Tract 9900, Ocean County, New Jersey   34.0         0.0
42455        Census Tract 9900, Salem County, New Jersey   34.0         0.0
43717         Census Tract 9902, Cayuga County, New York   36.0         0.0
43753     Census Tract 9900, Chautauqua County, New York   36.0         0.0
44169           Census Tract 9900, Erie County, New York   36.0         0.0
44290   Census Tract 9900.01, Jefferson County, New York   36.0         0.0
45051          Census Tract 9901, Kings County, New York   36.0         0.0
45282         Census Tract 9900, Monroe County, New York   36.0         0.0
45578         Census Tract 9901, Nassau County, New York   36.0         0.0
45579         Census Tract 9902, Nassau County, New York   36.0         0.0
45580      Census Tract 9903.01, Nassau County, New York   36.0         0.0
45581      Census Tract 9903.02, Nassau County, New York   36.0         0.0
45582         Census Tract 9904, Nassau County, New York   36.0         0.0
45932        Census Tract 9900, Niagara County, New York   36.0         0.0
46261        Census Tract 9900, Orleans County, New York   36.0         0.0
46291         Census Tract 9900, Oswego County, New York   36.0         0.0
46996         Census Tract 9901, Queens County, New York   36.0         0.0
47148       Census Tract 9901, Richmond County, New York   36.0         0.0
47710        Census Tract 9901, Suffolk County, New York   36.0         0.0
47873          Census Tract 9901, Wayne County, New York   36.0         0.0
48229  Census Tract 9901, Brunswick County, North Car...   37.0         0.0
48397  Census Tract 9901, Carteret County, North Caro...   37.0         0.0
48398  Census Tract 9902, Carteret County, North Caro...   37.0         0.0
48592  Census Tract 9901, Currituck County, North Car...   37.0         0.0
48602     Census Tract 9901, Dare County, North Carolina   37.0         0.0
48603     Census Tract 9902, Dare County, North Carolina   37.0         0.0
49139     Census Tract 9901, Hyde County, North Carolina   37.0         0.0
49140     Census Tract 9902, Hyde County, North Carolina   37.0         0.0
49622  Census Tract 9901, New Hanover County, North C...   37.0         0.0
49659   Census Tract 9901, Onslow County, North Carolina   37.0         0.0
49692  Census Tract 9901, Pamlico County, North Carolina   37.0         0.0
49718   Census Tract 9901, Pender County, North Carolina   37.0         0.0
50588          Census Tract 9900, Ashtabula County, Ohio   39.0         0.0
51327           Census Tract 9900, Cuyahoga County, Ohio   39.0         0.0
51402               Census Tract 9901, Erie County, Ohio   39.0         0.0
52195               Census Tract 9900, Lake County, Ohio   39.0         0.0
52328             Census Tract 9902, Lorain County, Ohio   39.0         0.0
52456              Census Tract 9900, Lucas County, Ohio   39.0         0.0
54626          Census Tract 9900, Clatsop County, Oregon   41.0         0.0
54650          Census Tract 9901.01, Coos County, Oregon   41.0         0.0
54660         Census Tract 9901.01, Curry County, Oregon   41.0         0.0
54707          Census Tract 9900, Douglas County, Oregon   41.0         0.0
54888             Census Tract 9900, Lane County, Oregon   41.0         0.0
54906          Census Tract 9901, Lincoln County, Oregon   41.0         0.0
55188        Census Tract 9901, Tillamook County, Oregon   41.0         0.0
56794       Census Tract 9900, Erie County, Pennsylvania   42.0         0.0
58635    Census Tract 9900, Newport County, Rhode Island   44.0         0.0
58805  Census Tract 9901, Washington County, Rhode Is...   44.0         0.0
58806  Census Tract 9902, Washington County, Rhode Is...   44.0         0.0
58938  Census Tract 9901, Beaufort County, South Caro...   45.0         0.0
59072  Census Tract 9901, Charleston County, South Ca...   45.0         0.0
59128  Census Tract 9901, Colleton County, South Caro...   45.0         0.0

In [72]:
df = df.drop(columns=['total_pop2', 'GEOID', 'Geographic Identifier - FIPS Code'])

In [73]:
df.columns

Index(['tract_geoid', 'All_Provider_Count', 'All_Providers', 'MaxAdDown',
       'MaxAdUp', 'AllMaxAdDown', 'AllMaxAdUp', 'Wired_Provider_Count',
       'Satellite_Provider_Count', 'Fixed_Wireless_Provider_Count',
       ...
       'pct_pop_60_to_64', 'pct_pop_65_to_69', 'pct_pop_70_to_74',
       'pct_pop_75_to_79', 'pct_pop_80_to_84', 'pct_pop_gt_85',
       'pct_pop_disability', 'pct_pop_households_with_kids',
       'Ookla Median Download Speed (Mbps)',
       'Ookla Median Upload Speed (Mbps)'],
      dtype='object', length=111)

In [74]:
df.to_csv("../data/fcc_census_2.csv", index_label=False)